### PR TITLE
RTL X(clear) Overlap Bug Fix

### PR DESCRIPTION
**Pull request by neeldoshii**
## Description
Originally the issue was occurring because the text was starting from right side and the image (X) was on top of it.  So a padding was implemented from right so now the X is not overlapped.

Issue #720 

## Testing Instructions

1. Open a podcast page
2. Tap into the search bar
3. Set a RTL language and start typing (Urdu or some language which stars from right to left (RTL))

## Screenshots or Screencast 
Tested on Emulator (Pixel 6)

--------------

Tested on Physical Device Realme Oppo cph1859

 
--------------

#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size (Tested with 200% font)
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by neeldoshii** [comment]
###What are this checks? and is this necessary required?
1. buildkite/pocket-casts-android/instrumented-tests Expected — Waiting for status to be reported
3. buildkite/pocket-casts-android/lint Expected — Waiting for status to be reported 
5. buildkite/pocket-casts-android/unit-tests Expected — Waiting for status to be reported

**Comment by neeldoshii** [comment]
I will be completing all the checks for the merge in the meantime.

**Comment by mchowning** [comment]
Thanks for the contribution @neeldoshii !

> ###What are this checks? and is this necessary required?
> 
> 1. buildkite/pocket-casts-android/instrumented-tests Expected — Waiting for status to be reported
> 2. buildkite/pocket-casts-android/lint Expected — Waiting for status to be reported
> 3. buildkite/pocket-casts-android/unit-tests Expected — Waiting for status to be reported

They are required, we just manually kick them off once we review the PR.

**Comment by neeldoshii** [comment]
> They are required, we just manually kick them off once we review the PR.

Can you help me how to complete this test? Any information will be much better. 😊
Thank You

**Comment by mchowning** [comment]
> Can you help me how to complete this test? 

Sorry I wasn't clear. There's nothing you need to do. When someone reviews the PR, they'll take care of kicking off the additional CI checks. 

For context, we do that for security reasons because we do not want code running on our CI server until it has been reviewed.

**Review by mchowning — APPROVED** [review]
Works great! Thanks for the contribution @neeldoshii !

I just updated your branch to bring in the latest changes from `main` and to add an entry to the changelog file. I'll kick off CI now so we can get this merged! 😄

**Comment by neeldoshii** [comment]
> Works great! Thanks for the contribution @neeldoshii !
> 
> I just updated your branch to bring in the latest changes from `main` and to add an entry to the changelog file. I'll kick off CI now so we can get this merged! 😄

Thank  You will work on more issues to make this app the best. Btw can I get an invite to the slack channel?

**Pull request merged**
