### PR TITLE
[Give Rating] Add action tapping to stars

### LINKED ISSUE #2638: Add taping action to stars to open rating screen
- See: p1723652426719639/1723638851.314939-slack-C05RR9P9RAT

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- Adds the action tapping to stars to open the rate screen
- We are going to keep the Rate button
- See: p1723652426719639/1723638851.314939-slack-C05RR9P9RAT

Fixes #2638

## Testing Instructions
1. Open an podcast to rate
2. Tap on stars
3. ✅ Make sure the rate screen is open
4. Back to the previous screen
5. ✅ Tap on rating average
6. ✅ Make sure the rate screen is open

## Screenshots or Screencast 
[Screen_recording_20240814_134952.webm](https://github.com/user-attachments/assets/3fa0991c-112f-4ade-a8ad-b464d14aad9f)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/61">7.70 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by geekygecko — COMMENTED** [review]
If possible it would be good to have a wrapper so there is only one clickable area. When using TalkBack there are three separate click targets and some of them aren't labelled. Can we also have a touch ripple similar to the rate button?

Screenshot 2024-08-15 at 11 20 37 AM

Screenshot 2024-08-15 at 11 21 18 AM


https://github.com/user-attachments/assets/5f940c73-051d-487a-996c-26ce8a6fa6da

**Comment by mebarbosa** [comment]
> If possible it would be good to have a wrapper so there is only one clickable area. When using TalkBack there are three separate click targets and some of them aren't labelled. Can we also have a touch ripple similar to the rate button?
> 
> Screenshot 2024-08-15 at 11 20 37 AM Screenshot 2024-08-15 at 11 21 18 AM
>  Screen_recording_20240815_111807.mp4

Hey @geekygecko I've pushed the changes wrapping them into a row and added content description for them

**Comment by geekygecko** [comment]
The alignment of the stars and the number doesn't seem right.

Screenshot 2024-08-16 at 3 50 17 PM

It would nice if we can add some padding to the touch state. 

Screenshot 2024-08-16 at 3 52 44 PM

**Review by geekygecko — APPROVED** [review]

**Pull request merged**
