### PR TITLE
Display both Up Next and Profile as tabs

### PR DESCRIPTION
**Pull request by ashiagr**
Part of #2081 
## Description

This 
- Reverts changes to move Profile to the toolbar (including cast icon, search bar and empty state mini player changes) 
   (Internal Ref: pdeCcb-4tX-p2#comment-4063, p1714726940370859/1714538638.124039-slack-C05RR9P9RAT)
- Adds Chromecast button on the Up Next tab screen toolbar

** It does not apply design changes on the Up Next tab screen yet. 

#### FF enabled
1. Open the app
2. ✅ Notice that there is a new Up Next tab in the bottom bar
3. Tap on Up Next tab
4. ✅ Notice that Up Next screen is displayed with a Chromecast button in the toolbar
5. ✅ Notice that `up_next_tab_opened` event is tracked
6. Go to Podcasts tab
7. ✅ Notice that the search and Chromecast buttons are displayed on the toolbar
8. ✅ Notice that Profile tab is shown in the bottom tab
9. ✅ Smoke test that mini-player can be tapped and dragged properly

#### FF disabled
1. Turn off `Show Up Next in tab bar` feature flag in Profile -> Settings -> Beta features
2. Kill and restart the app
3. ✅ Notice that Up Next tab is not shown in the tab bar

#### FF enabled
out

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md -  N/A (Feature in progress)
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews N/A
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes... (N/A - no changes to Up Next tab screen)

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — COMMENTED** [review]
Nice work reverting this!

I noticed one small that I am not sure if it's related to this PR. The `Nothing in Up Next` card has no brackground for some themes. See dark and light theme to compare:

dark
light

**Comment by geekygecko** [comment]
This is only minor but I'm not sure the Up Next icon is correct. I have installed it on my device and the lines look really thick compared to the design. It also looks different from the same Up Next icon in the mini player which makes it stand out. Is it possible to try using the icon from the mini player?

My device
Screenshot 2024-05-07 at 7 23 47 AM

The design
Screenshot 2024-05-07 at 7 26 10 AM

**Comment by ashiagr** [comment]
@geekygecko 👋 

I've replaced upnext tab icon in [860b8c2](https://github.com/Automattic/pocket-casts-android/pull/2161/commits/860b8c27b05c36e8f56a04058686c276d24f9d17). Here's how they look now:

Unselected | Selected
---|----
upnext tab | upnext tab selected

@mebarbosa 👋 

>  The Nothing in Up Next card has no brackground for some themes. See dark and light theme to compare:

The Up Next tab currently displays the existing Up Next screen with no design updates. I'll update the design in another PR.  Thanks for reporting it anyway 🙏 , it might have slipped my testing.

**Comment by geekygecko** [comment]
> I've replaced upnext tab icon in [860b8c2](https://github.com/Automattic/pocket-casts-android/pull/2161/commits/860b8c27b05c36e8f56a04058686c276d24f9d17). Here's how they look now

Thanks, the icon looks great.

**Review by mebarbosa — APPROVED** [review]

**Pull request merged**
