### PR TITLE
Intro offer: Update user eligibility

### PR DESCRIPTION
**Pull request by mebarbosa**
This is part of: #1728

## Description
- This PR implements the user eligibility offer for intro plus offer
```
The offer should be shown to any user that never had this subscription before (this case is com.pocketcasts.plus.testfreetrialoffer) or Plus activated (lifetime members).
```

## Testing Instructions
- git apply [patch](https://github.com/Automattic/pocket-casts-android/files/14036750/new_patch.patch)
- Have the In-app billing sandbox setup

#### 1.1 Free account

1. Have `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` set to `true`.
2. Log in with a free account
3. Profile -> Account
4. You should see the Intro offer ✅

#### 1.2 Plus account
1. Have `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` set to `true`.
2. Log in with a plus account
3. Profile -> Account
4. You should not see the Intro offer ✅

#### 1.3 Lifetime member
1. Have `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` set to `true`.
2. Log in with lifetime member account
3. Profile -> Account
4. You should not see the Intro offer ✅

### 2.1 Fresh account
1. Have `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` set to `false`.
2. Log in with a free account that never had a subscription before
3. Profile -> Account
4. You should see the trial offer ✅

### 2.2 Fresh account
1. Have `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` set to `false`.
2. Log in with a free account already had a subscription before
3. Profile -> Account
4. You should see not the trial offer ✅

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews

### CODE REVIEW

**Review by Mukuljangir372 — APPROVED** [review]

**Comment by ashiagr** [comment]
A couple of feedback/ questions:

**1.2 Plus account**
You should not see the Intro offer ❌ 

I was able to see the intro offer for a Plus account expiring in less than 30 days. 



---------

**Offer eligibility**
```
The offer should be shown to any user that doesn't have a current subscription or Plus activated (lifetime members).
```

Can a user who doesn't have an active subscription claim the offer just once or multiple times?

**Review by MiSikora — COMMENTED** [review]
I found an issue with a free account.

1. Sign in.
2. See the offer.
3. Close the app.
4. Open the app.
5. Go to `Account`.
6. The offer is not available.
7. Close the app.
8. Clear app data.
9. Open the app (you're still signed in).
10. The offer is available again.

The same can happen if in 8th step instead of clearing app data we reinstall the app and sign in again.

https://github.com/Automattic/pocket-casts-android/assets/30936061/c219ed95-7ebe-4d5e-8675-580a7160e478

**Comment by mebarbosa** [comment]
Hi @MiSikora and @ashiagr ! Since I was not able to work on this project last week I could not update this PR. The rules for the user eligibility changed and I only updated the PT. I will start working on this again and update the PR's descriptions and testing steps. Thanks for reviewing this

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/45">7.57</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mebarbosa** [comment]
I am closing this PR since we have new rulers for user eligibility and I will open another one to avoid any confusion

**Pull request closed without merging**
