### PR TITLE
Fix artwork aspect ratio

### LINKED ISSUE #1719: Horizontal artworks are cropped in the player view
### Description

When a podcast episode has a horizontal artwork it is not displayed correctly. It is cropped instead of being fitted. I did some investigation and the bug was introduced with the fix in #1665. However, digging a little bit more it turns out that `coil.transform.RoundedCornersTransformation` is at fault. Commenting out this line fixes the issue.

https://github.com/Automattic/pocket-casts-android/blob/17d049450a9419d8aa6f9f84fabf67b6704e2b7c/modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt#L372

Supposedly we can fix it with a custom transformer mentioned here https://github.com/coil-kt/coil/issues/421#issuecomment-640133205. The linked implementation is no longer valid as the API changed but it can be probably used as an entry point for our implementation if I solve it this way.

I also tried updating Coil but that didn't help.

### Step-by-step reproduction instructions

1. Play [this episode](https://pca.st/episode/c7bc3a08-17b7-48c8-b5b9-dbdfd63211f4).
2. Open up the player.
3. You'll see a cropped artwork.

### Screenshots or screen recording

| With transformation | Without transformation |
| - | - |
| Screenshot_20240119-124053 | Screenshot_20240119-124814 |

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 13, Pocket Casts `7.55-rc-2 (9184)`

### PR DESCRIPTION
**Pull request by ashiagr**
## Description

This fixes horizontal artwork aspect ratio by using a modified version of Coil's rounded corners image transformation that does not crop to the target size. 

I'm not yet fully sure that removing cropping to the target size during transformation can cause any issues. In Test.3, I tested loading a very large image and noticed that it didn't crash the app. 

Also, it seems another image loading library, [Glide does not crop to the target size](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L581) in rounded corner transformation.

Fixes #1719

### Test.1 Horizontal Image
1. Play this episode with a horizontal artwork: https://pca.st/episode/c7bc3a08-17b7-48c8-b5b9-dbdfd63211f4
2. Open full-screen player
3. ✅ Notice that full artwork is shown maintaining its aspect ratio

### Test.2 Square Image
1. Play this episode with a square artwork: https://pca.st/episode/e548fdef-c912-4468-9594-34b492644107
2. Open full-screen player
3. ✅ Notice that full artwork is shown maintaining its aspect ratio

### Test.3 Large image
1. Play this episode with a very large artwork of size 5400 x 5400: https://pca.st/episode/c00fd075-ee5c-42a4-94e1-6b7afeb8ed1b
2. Open full-screen player
3. ✅ Notice that full artwork is shown maintaining its aspect ratio and the app does not crash

### Test.4 Small device
1. Repeat all above tests on a small device (5.2" 1080x1920)
2. ✅ Notice that all tests pass and no scrolling is required as reported here: p1706158031515139-slack-C02A333D8LQ

## Screenshots or Screencast 

Pixel 7
Horizontal | Square
---|---
| 

Small device (5.2" 1080x1920)
Horizontal | Square
---|---
  | 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>RoundedCornersTransformation</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — APPROVED** [review]
LGTM! Tested on Pixel 6 and an emulator with screen size of 5.0".

Maybe we should also apply it here?

https://github.com/Automattic/pocket-casts-android/blob/1832cdb2b320a48bc8ca9e92377bb64f290204db/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt#L110

I encountered one issue. I was not able to use a deep link for the second podcast effectively (https://pca.st/episode/e548fdef-c912-4468-9594-34b492644107). The app opened but didn't show any podcast or episode. I didn't investigate it though.

**Comment by CookieyedCodes** [comment]
Also check landscape 😅

**Comment by ashiagr** [comment]
> Maybe we should also apply it here?

Applied in https://github.com/Automattic/pocket-casts-android/pull/1742/commits/d3a1bf9b52a83d44900b6a0775508e83300c9009

> I encountered one issue. I was not able to use a deep link for the second podcast effectively (https://pca.st/episode/e548fdef-c912-4468-9594-34b492644107). The app opened but didn't show any podcast or episode. I didn't investigate it though.

It seems that the app cannot open native episode sharing URL of the format like: https://pca.st/episode/e548fdef-c912-4468-9594-34b492644107 if the episode does not exist in the app's database. It cannot open its podcast as the link does not include any podcast id. It can however open sharing URLs of the format: https://pca.st/cdkzkdzu. I'll check how iOS handles such URLs and open an issue. 


Including screenshots from landscape mode:



They look good to me.

**Comment by CookieyedCodes** [comment]
Looking good ❤️❤️

**Pull request merged**
