### PR TITLE
Linter Check on the PR Template 

### PR DESCRIPTION
**Pull request by Mzazi25**
## Description

Added  `./gradlew :spotlessApply` linter check on the PR template

Fixes # 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Review by mchowning — COMMENTED** [review]
Thanks for this! Adding the reminder to the PR checklist is a good idea. Just curious, why did you choose to create a shell script and add an instruction for running that to the PR description instead of giving the gradle shell command in the PR description?

**Comment by Mzazi25** [comment]
> Thanks for this! Adding the reminder to the PR checklist is a good idea. Just curious, why did you choose to create a shell script and add an instruction for running that to the PR description instead of giving the gradle shell command in the PR description?

@mchowning My bad. You are right, I should have written the the shell command on the PR description. 
should I change it?

**Comment by mchowning** [comment]
Using the shell script is fine, but I would lean toward not using a separate script if there's not a clear benefit to doing so. The fewer things we have to maintain the better.

**Comment by mchowning** [comment]
👋 @Mzazi25 ! Would you mind going ahead and removing the shell script here? The more I think about it, the more I think it would be better to not have something else to maintain. Let me know if you disagree though.

**Comment by Mzazi25** [comment]
> would

Okay, Its fine. I agree with you, the less things to maintain, the better. So should I close this PR?

**Comment by mchowning** [comment]
What about updating the PR to remove the shell script and instead directly referencing the gradle spotless command in the PR template? I do think that this is something that trips up a lot of contributors, so it seems like a good idea to point out the linter like you're doing.

**Comment by Mzazi25** [comment]
I have update the PR. 
Removed the shell script and added the linter check on the PR template.

**Review by mchowning — APPROVED** [review]
I did a small tweak to remove the `:` from the command. Thanks for contributing this change—I think it will help out a lot of people! 🙇

**Pull request merged**
