### PR TITLE
Bring back old widget and hide new ones

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

After a lot of feedback about new widgets this brings back the old one and hides new ones until we have the designs and time to work on them.

There are some small differences (like a bit different play icon) but it behaves virtually the same as the XML one.

### Widget

Perform regression tests on the widget and compare it with the XML one. Check theming, showing artwork, and playback controls.

### Migration

1. Install the app from 327bc2107d7666d22ff2f5f5e3fab15585341500.
2. Add the widget.
3. Add something to your queue so that the widget display something.
4. Install the app from `task/old-widget`. You need to install the app from CLI and not Android Studio.
5. You should still have the old widget on your screen.

### What's New

1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/15061094/whats_new.patch).
2. Install and open the app.
3. You should not see "What's New" popup about widgets.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          4 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>MediumPlayerWidgetReceiver</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>OldPlayerWidget</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>OldPlayerWidgetState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Adapter</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/51">7.62 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by MiSikora** [comment]
After seeing #2096 I'm worried I might need to bring back the old XML implementation

**Comment by MiSikora** [comment]
@mebarbosa Please test again. I removed custom Glance implementation. Bugs you found would be easy to fix but due to #2096 I decided to not use Glance and bring back the old widget.

**Review by mebarbosa — APPROVED** [review]
I can confirm the buttons are working as expected now

**Pull request merged**
