### PR TITLE
Deselect Chapters - What's new updates

### PR DESCRIPTION
**Pull request by ashiagr**
Part of: #1807

## Description
This updates What's new version and now display What's new for Deselect Chapters.

> [!IMPORTANT]
> - Do not merge until feature needs to be enabled
> - Update the following values before merging

### TODO
1. Update `DESELECT_CHAPTERS` in `Feature.kt `
    `defaultValue=true`
    `hasFirebaseRemoteFlag=true`
     `tier = FeatureTier.Plus(ReleaseVersion(7,60))` <- If the feature is Patron-exclusive for 7.60 release. The flow has been tested as part of https://github.com/Automattic/pocket-casts-android/pull/1896
2. We may also need to change  `deselect_chapters` remote config key in `Firebase` (Internal ref: p1709746251054939/1709746242.376339-slack-C06EHRAPW12) and update it in `Feature.kt`
3. Add Changelog entry for the appropriate release when the feature needs to be enabled

## Testing Instructions
1. Install the app from a previous commit like 85f03687
2. Install the app from this PR
4. Launch the app
5. ✅ Notice that you see What's new for Deselect Chapters

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — APPROVED** [review]
LGTM 💯

**Comment by ashiagr** [comment]
https://github.com/Automattic/pocket-casts-android/pull/1940/commits/7290942fc9af432b9c70bb6f8245748a0619cf3d Replaced remote key p1710478199550069/1709746242.376339-slack-C06EHRAPW12
https://github.com/Automattic/pocket-casts-android/pull/1940/commits/546414fded41348f59b91f2e2f4b1444561df71f Updated feature tier to include patron early access release pdeCcb-4ud-p2#comment-3756

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
