### PR TITLE
Coroutine Rule Cleanup on Viewmodels

### PR DESCRIPTION
**Pull request by Mzazi25**
## Description
This PR cleans up main coroutine rule on the AdvancedSettingsViewmodel, StoriesViewmodel, ManualCleanupViewmodel, StorageSettingsViewModel, AdvancedSettingsViewModel and SearchViewModelViewModel Tests. 

Fixes # N/A

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Review by ashiagr — APPROVED** [review]
Thank you for this contribution, @Mzazi25! 

The only feedback I have is that `MainCoroutineRule` is duplicated across modules. It would have been great if it could be reused from a common location. But I wouldn't hold off merging this PR as it might be a bit tricky to do that and can be taken up separately.

**Comment by Mzazi25** [comment]
Sure no problem. I can try checking it up. Also if you have any other tasks, I would be glad if you could assign me. 
Thanks

**Comment by CookieyedCodes** [comment]
@Mzazi25 theirs some small things that I would like to be added to the app could I ask you to do it 😅 (I know their simple code wise but I don't trust myself)

**Comment by Mzazi25** [comment]
Sure. I am up for it

**Comment by CookieyedCodes** [comment]
It's alot of small little things 😅 -at least for the first 7 & if it's not possible that's perfectly fine too tho let me know why so I can finally drop my dreams but most should be simple enough :) 
If you want any UX let me know I can help with that :)


1. +1 minute add to sleep timer 



2. If the custom timer is <5 min the + - goes down to 1 min increments



3. No of episodes sleep timer -sleeps after a number of episodes-
(I would do this with a +- next to end of episode once two+ episodes are added a new option would appear above end of episode that says end in 'num' episodes)
I would add a no of episodes remaining popup screen with the options to convert to sleep timer(based off last timer set),
 +1 episode
+3 episodes 
+ 5 episodes
+Num episodes &
End of current episode/cancel timer 


(
It could also be put/pushed on this screen truthfully 😅)


4. Long press on the playback effects icon -3 to 5 seconds- and it will enable local playback effects on that podcast 


5. Filter auto download being able to be set to a custom number or at least 3 if that's not possible 😅 (bonus points for local/global auto archive/episode limits also getting custom NUM options)


6. If a selected option in multiselect is long pressed, select all below & select all above become deselect all below & deselect all below. (Maby also add a select all/deselect all option in the middle with this popup too 🤔)


7. Hitting search icon in the bottom bar while in discover opens up the search menu & keyboard (be aware the reverse is somewhat allready true but the team wants discover to reload when returning to the page 😉)



...


Some bigger ones don't worry if not possible truthfully I'll get them to do it eventually 😅

8. Local auto archive by word
Reads tital/shownotes(when downloaded) if word is detected the episode will be auto archived (might require scripting from what I've heard, I would do it with "" on the word with each word & with a semicolon; used to break up the words). I want this mainly to get rid of repeat episodes


9. A timetags screen if shownotes have rss it will make a new swipe page
 (based off chapters with the same skipping functions with the tita taken from the words following the timetag until the next timetag, if the podcast allready has chapters this page wouldn't appear)


10. Upnext filter/save upnext as a filter(keeps upnext sort order)


11. Downloads filter pill has the following check boxes
- [ ] include loose downloads (non subscribed basically 
- [ ] include cloud files 
- [ ] include local files (not uploaded to cloud)
 (dosen't have to sync as I think it only has to apply to the local device)


12. Folders filter pill with sort option to go of folder sort (this should sync tho so maby not for you)


13. Add next oldest episodes to upnext/uplast (based off selection, ignores archived episodes)


14. Folders for Files (it was built with this in mind from my understanding when talking to the original dev but still hasn't been implemented)


15. The ability to deselect chapters from the chapter view (the team dose what to make this a plus feature on the iOS side, some community movement on this a year ago nearly but never finished, no movement on Android unfortunately)


16. Custom coulors for uploaded files/folders (probably requires backend tho)


Sorry about that I get passionate 😅
Seriously if it's gonna take too much of your time don't worry about it tho 😉, I would like your thoughts regardless if possible ❤️❤️

**Comment by Mzazi25** [comment]
Don't drop the dream too soon😅
The tasks are interesting to work on. I am ready to put in the work.
So for each task I can send a PR separetely. 

The first 7 are pretty straightforward. The other bigger ones I will still get them done. In case I run into any challenges, I will give a heads up, but its all manageable. 

Let me get started.

**Comment by CookieyedCodes** [comment]
@Mzazi25 oh I won't drop hope, just need a passionate person to work on my niggles, enjoy setting up the PRs, I'll keep an eye on any progress regardless 😅 (their might be a few more if you get those done 😉 ❤️)

**Comment by Mzazi25** [comment]
@CookieyedCodes Sure thing

**Comment by CookieyedCodes** [comment]
So 
13 might be rectifyed soon with this feature being added to iOS & android https://github.com/Automattic/pocket-casts-ios/pull/932 sure 13 it would still be a nice option to have regardless but not as much a priority with a feature like this 😉 ❤️

btw are you on the Pockectcasts slack -email support to enquire-, it might be an easier way of contacting you if you need help/UX advice:)

**Comment by Mzazi25** [comment]
No I am not 
Here is my mail 
langat.caleb95@gmail.com

**Comment by CookieyedCodes** [comment]
Email support & inquire I don't have admin rights -not a pockecasts team member 😅, just a power user who's very attentive on this app :)-

**Comment by Mzazi25** [comment]
Just got in 
Thanks

**Comment by ashiagr** [comment]
Thanks for the list of tasks @CookieyedCodes! @Mzazi25 can help us with the smaller ones (1-6). Thank you @Mzazi25 for lending a hand. 

For the 7. one, we're still not clear about when we should refresh the `Discover` tab if we do this. Ideally, it should be refreshed on a user action like a double tap on the `Discover` tab, or maybe a pull-to-refresh rather than every time on returning from a search. I can continue this discussion on your [idea](https://github.com/Automattic/pocket-casts-android/discussions/470) and suggest adding a pull-to-refresh prior to adding such a behavior. 

Also, can we add the larger ones as ideas to the discussion board which has more visibility compared to this isolated task,  where they can first be discussed (and possibly voted on 😄)? 

We're lucky to have an awesome community, get such great suggestions, and enthusiastic contributors! The more votes we get (both publicly and internally through tickets), the better we'll be able to prioritize them when it comes to decisions related to design, backend support, and getting feature parity with iOS. This is the same way we've prioritized the most requested features, such as the [Wear OS app](https://github.com/Automattic/pocket-casts-android/issues/468), [Bookmarks](https://github.com/Automattic/pocket-casts-android/issues/867), an automatic playlist (task#13 😉), and Ratings. 

> Sorry about that I get passionate 😅

You come up with great ideas @CookieyedCodes! So keep them coming, and the more votes you can gather, there are more chances of them getting included. We really appreciate your efforts. 🙏

**Comment by Mzazi25** [comment]
Thanks for the feedback @ashiagr 
I will complete the tasks(1-6) as suggested by @CookieyedCodes

**Comment by CookieyedCodes** [comment]
@ashiagr 
Ya I've been working on it with him on the slack 😉 ❤️

Regarding 7 would refresh not be possible on a return to a page? But that's fair enough if refresh can't be done on return, you do make me think that pull to search might be a better action tho (might be better action once people get used to it tbc because it gives the user time to think & is quicker as tada keyboard 🤔 & dosen't disrupt the refresh + you want to keep your refreshes up)

Regarding the bigger ideas, I agree completely tho most of these ideas I have had on the discussions GitHub (ignored mostly unfortunately:( ), your slack & being added to the subreddit & paying attention to your twitter support for the many of the past few years (less so twitter this year because Elon). 

So I'm personally a tad soso on a private board/forum(that's mostly being used for support) approach as that dosen't help with long term transparency & feels like a bit of a black box -github dose help somewhat- I'm much more favouritable a public roadmap which shows priority & upvotes/upcomeing/focus built in kind of like what epic games dose with their store/Engine -& it's perfectly fine if its not possible just give a reason why it's not possible in my view-

(& obviously have a private board for your own prioritys) (I'm just a tad annoyed by the black box approach that be all truthfully, but I accept you can't focus on everything) (and if you do have a more public board do let me know :) )

Again I call them cookieyedniggles because they are the little UX things 😅 that enhance the app, and sure big ones can come whenever mostly it's just my product mind thinking 😅
 (Tbc tho folder pills with sort order going off the folder order is a big one for me & alot of users & would be amazing with autoplay 😉) (word auto-archiveing truthfully is the biggest one for me) & the stuff you have listed is all long requested too especially wear os so I get it, it's alot to prioritize.

(Thanks @Mzazi25 for helping with the niggles tho tbc ❤️❤️)


https://docs.google.com/document/d/1moKeBOc_kJc0UcIJjAowkOb-yXC1YANcv2wOXdEhDAs/edit?usp=drivesdk I'm going to comb through this list I did a few months ago this afternoon & just stoplight it. (which I think I did for you or whoever was on doing the research at the beginning of the year/Dec)

**Comment by ashiagr** [comment]
> Regarding the bigger ideas, I agree completely tho most of these ideas I have had on the discussions GitHub (ignored mostly unfortunately:( ), your slack & being added to the subreddit & paying attention to your twitter support for the many of the past few years (less so twitter this year because Elon).

> So I'm personally a tad soso on a private board/forum(that's mostly being used for support) approach as that dosen't help with long term transparency & feels like a bit of a black box -github dose help somewhat- I'm much more favouritable a public roadmap which shows priority & upvotes/upcomeing/focus built in kind of like what epic games dose with their store/Engine -& it's perfectly fine if its not possible just give a reason why it's not possible in my view-

There’s nothing like it’s not possible @CookieyedCodes. It’s just that we haven’t been able to make it public yet. Meanwhile, we have a public ideas board on `GitHub` where everyone can vote. Wear OS app was a perfect example where we could see a big interest publicly. It can be done to other ideas as well. I can also nudge our support team to request users who come through internal tickets to personally vote on the board as we cannot do that on their behalf on `GitHub`. 

Usually, there are multiple ongoing projects on `GitHub`, so you can be aware of the priorities of the team but I agree we can be better at long-term transparency. On behalf of the team, I can say that we really don't want to have any kind of a black-box approach, open-sourcing the apps is a testament to it.

> Again I call them cookieyedniggles because they are the little UX things 😅 that enhance the app, and sure big ones can come whenever mostly it's just my product mind thinking 😅
(Tbc tho folder pills with sort order going off the folder order is a big one for me & alot of users & would be amazing with autoplay 😉) (word auto-archiveing truthfully is the biggest one for me) & the stuff you have listed is all long requested too especially wear os so I get it, it's alot to prioritize.

They're great ideas! Could you just add the bigger ones to the ideas board if they're not already? I really like the `cookieyedniggles` name 😆 and you can see that smaller ones already have a green signal.

We're lucky to have such a passionate community that wants to make the app feature-rich and has tons of ideas for that. Really, thanks for all the support! ❤️

**Comment by CookieyedCodes** [comment]
I get ya, just something to do eventually before 2023 preferably 😅 😉 (is their something particularly that is holding you back on it btw, I find it a tad weird that automattic wouldn't be for it)

Care to share where that community board is on github is I don't see it on mobile 😅



Their only niggles because of your nearly perfect app 😅 ❤️

**Comment by ashiagr** [comment]
> Care to share where that community board is on github is I don't see it on mobile 😅

It's the discussion tab, feature request category:

Screenshot 2023-07-07 at 5 26 59 PM

**Pull request merged**
