### PR TITLE
Add What's New for Reimagine Sharing

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

See for specs: p1724799780302989-slack-C02LGFKP0AE

## Testing Instructions

1. Install the app from 028c4652f9f71d1b4d28bd75722341f6e7d93f72
2. Open the app.
3. Make sure that you close the onboarding screen.
4. Install the app from this branch.
5. Open the app.
6. You should see "What's New"

## Screenshots or Screencast 

Screenshots do not account for [1e382c9](https://github.com/Automattic/pocket-casts-android/pull/2745/commits/1e382c972cfdd41676c3903f98661d90c8668344)

| Animation | Small device | Fold device |
| - | - | - |
| anim | small | fold |

## Checklist
- [x] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] ~I have considered whether it makes sense to add tests for my changes~
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SocialPlatform</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by geekygecko — APPROVED** [review]
Amazing!

**Comment by aurarora** [comment]
Is this typo known?
> We've also **made easier** to share…
instead of 
> We've also made **it** easier to share…

**Comment by MiSikora** [comment]
> Is this typo known?

It is now. Thanks for pointing it out.

**Pull request merged**
