### PR TITLE
Update horologist version (and libraries that matches this version)

### PR DESCRIPTION
**Pull request by ashiagr**
## Description

This updates horologist lib to ~the latest `v0.5.14`~ the latest `0.4.x` version of `0.4.17` from the current `v0.4.10`. Below essential libraries are also upgraded to match this version:

`kotlin`: `1.7.0` to `1.9.0`
`ksp`: `1.7.10-1.0.6` to `1.9.0-1.0.13`
`compose-kotlin-compiler`: `1.3.0` to `1.5.2 `(refers [Compose Compiler to Kotlin Compatibility Map](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#:~:text=1.5.2,1.9.0))
`hilt`: `2.43.2` to `2.49`
`hilt-compiler`: `1.0.0` to `1.1.0`
`media3`: `1.0.0` to `1.2.0`

In addition, we had to update the compileSdk.

#### Release notes

Horologist: https://github.com/google/horologist/releases
Kotlin: https://github.com/JetBrains/kotlin/releases?page=3
Kotlin Compiler: https://developer.android.com/jetpack/androidx/releases/compose-compiler
Hilt Android: https://mvnrepository.com/artifact/com.google.dagger/hilt-android, https://github.com/google/dagger/releases
Hilt Compiler: https://developer.android.com/jetpack/androidx/releases/hilt

## Testing Instructions
1. Smoke test the phone, automotive, and especially the watch app for any regressions since this is updating quite a few dependencies.
2. Redo the testing steps for https://github.com/Automattic/pocket-casts-android/pull/1636 to make sure that horologist is properly keeping the chips fully visible.
3. Verify that all screens which are scrollable display a scrollbar as you scroll them.

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] for accessibility with TalkBack

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mchowning** [comment]
Merging these changes with `main` resulted in a fair number of merge conflicts, so I just cherry-picked the relevant changes over to a new branch built off of `main` and opened [a PR](https://github.com/Automattic/pocket-casts-android/pull/1641) for that. If that PR looks ok, I think we can close this.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mchowning** [comment]
👋 @ashiagr !

I have tested this a fair bit on phone and automotive. 

I have tested the wear app on a Pixel 1 watch, the large watch emulator with the smallest text size, and the smallest watch emulator with the largest text size. In addition to smoke testing, I paid special attention to the scrollbars and any chips that might be clipped and I saw no issues.

The one issue I am seeing on the watch is that if you start playback without an available output device (i.e., no Bluetooth headphones), and then you back out of the selection screen, the app displays as if it is playing even though it is not playing. 

https://github.com/Automattic/pocket-casts-android/assets/4656348/959aea2b-9fbc-494c-8cb8-852f7d09d496

I have seen this both on the emulator and on my Pixel 1 watch, but I haven't isolated the cause yet. I'll take a closer look when I pick this up tomorrow.

**Comment by ashiagr** [comment]
👋

I reverted media3 changes as switching to horologist 0.4.17 did not require those changes. I smoke-tested the apps and found them working.

Besides the tests I conducted in this PR: https://github.com/Automattic/pocket-casts-android/pull/1641#pullrequestreview-1794122355 targeting `main`, which passed for this PR targeting `release/7.54`, I also tested scrolling on the launch screen, and with text set to a minimum I can see the scrollbar:

https://github.com/Automattic/pocket-casts-android/assets/1405144/70365432-c937-4032-a6e6-f931545d269d

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mchowning** [comment]
Before opening https://github.com/Automattic/pocket-casts-android/pull/1643, I initially pushed those changes onto this branch, but then I realized that they made more sense as a separate PR so I force-pushed this branch back to c04c011 , (which is where it was before my push), and moved those changes to #1643.

**Review by mchowning — APPROVED** [review]
I've smoke-tested the phone, automotive, and watch apps and observed no issues from these changes. I've particularly looked for issues with the scrollbar not showing up and chips being clipped by testing large watch screens with small fonts and small watch screens with large fonts. I've also tested on a physical watch checking for issues. Everything looks good.

**Review by Mukuljangir372 — APPROVED** [review]

**Pull request merged**
