### PR TITLE
Update profile navigation

### PR DESCRIPTION
**Pull request by ashiagr**
Part of: #2081 

## Description
This updates profile navigation from the profile menu.

#### Feature Flag ON

1. Open the app
2. Tap Profile menu
3. ✅ Notice that Profile screen opens with a close button
4. Tap on close button
5. ✅ Notice that Profile screen is closed
6. Re open Profile screen
7. Navigate to another screen from Profile screen
8.  ✅ Notice fragments are added as follows:
- Added over tabs
   - Account Details
   - Help & feedback
   - Setttings
   - Stats

- Added behind tabs so that playing an episode from these screen is reflected on the mini player
   - Downloads
   - Files
   - Starred
   - Bookmarks

    These are removed from back stack on switching to another tab to prevent weired state noticed in https://github.com/Automattic/pocket-casts-android/pull/2102#pullrequestreview-2019549512.

#### Feature Flag OFF

1. Turn off `Show Up Next in tab bar` feature flag in Profile -> Settings -> Beta features
2. Kill and restart the app
3. ✅ Notice that navigation from profile tab work as before

## Screenshots or Screencast 

https://github.com/Automattic/pocket-casts-android/assets/1405144/984a4852-d135-4353-973a-74793fec0b28

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — COMMENTED** [review]
It works as described but I'm not sure about one behavior. When I go to the settings from the profile and then go back I find it a bit not intuitive that the profile is no longer there. It might the case for all 4 "over tabs" screens but it is especially noticeable for settings. Is this expected?

I also think that having coming back to the profile might be hard implementation-wise because it is now a bottom sheet.

**Comment by ashiagr** [comment]
> having coming back to the profile might be hard implementation-wise because it is now a bottom sheet. So making it "persistent" might be challenging.

That's correct. I have not been able to find a good way to do this, so I'm dismissing Profile before navigating to any other screen.

> When I go to the settings from the profile and then go back I find it a bit not intuitive that the profile is no longer there. It might the case for all 4 "over tabs" screens but it is especially noticeable for settings.

I'll keep the PR open and see if I can improve it or add it to a nice-to-have list.

**Review by MiSikora — APPROVED** [review]
Ok, I'm happy to approve it knowing that we are aware of it. We can wait with merging.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
@MiSikora 👋 

I've updated the profile menu navigation so that fragments added `overTabs` (now renamed `overBottomSheet`) will have the profile screen in the back stack.

https://github.com/Automattic/pocket-casts-android/assets/1405144/03227ba2-f8d7-4da5-a355-474b3edcd68b

Can you take a look?

**Review by MiSikora — APPROVED** [review]
Yup, nice works. Thanks for changing that. 👍

**Pull request merged**
