### PR TITLE
Fix Lint issues

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

* Fix some Lint issues related to images.
* Ignore `InvalidPackage` and `ObsoleteLintCustomCheck` as creating a baseline for them them relies on Gradle hashes.
* Ignore `ConvertToWebp` as creating a baseline for it has nondeterministic output.
* Change Lint to not treat warnings as errors. I initially though it would be a good idea but after a couple of PRs I no longer thinks so. Most of these warning are harmless and they only make us constantly update baseline files.

## Testing Instructions

CI checks are enough.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
WDYT about rebasing over https://github.com/Automattic/pocket-casts-android/pull/2301 ? It updates lint and addresses `ObsoleteLintCustomCheck`.

**Comment by MiSikora** [comment]
If it is about git conflicts I don't mind resolving them myself in #2301. They are going to happen anyway so it doesn't really matter which PR is merged first.

**Comment by wzieba** [comment]
I was thinking more that with updated lint we won't have to disable `ObsoleteLintCustomCheck`, but it's a minor. I'm all good with merging this PR first. Conflicts should be minimal and can be addressed with `updateBaseline` task.

**Comment by MiSikora** [comment]
Got it. I think we still should add this issue to the ignore list to prevent future regressions.

**Review by ashiagr — APPROVED** [review]

**Pull request merged**
