### PR TITLE
Implement Large Player widget

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This targets a separate branch instead of `main` because widgets cannot be feature flagged as they are compile time dependent. Once all features are implement I will make a PR for the `task/widgets` branch.

Designs: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1044_7170

There are some known issues:

1. Sometimes artwork doesn't load and placeholder is displayed instead. Even though the `Image` composable receives a correct `ImageProvider` it still doesn't update. It might be a bug withing the `Glance` library. However image loads correctly once the playback is resumed.
2. Widget's preview and placeholder are currently not implemented. Internal ref: p1711476556931619/1711396714.667229-slack-C05RR9P9RAT

This PR also improves accessibility by using better colors for buttons.

## Testing Instructions

There are many things to test with this widget and it's hard to provide all instructions. Do some monkey tests on the widget.
1. Play episodes from the queue.
2. Change queue in the app and see if the widget updates.
3. Control playback.
4. See if time left updates (it updates in 5 second increments).

### Demo

https://github.com/Automattic/pocket-casts-android/assets/30936061/500005aa-9a1d-4c7b-bc2e-d8910027dfcb

### Dark and light mod

| Dark | Light |
| - | - |
| Screenshot_20240328-143325 | Screenshot_20240328-143334 |

### Dynamic themes

| A | B | C | D |
| - | - | - | - |
| Screenshot_20240328-143143 | Screenshot_20240328-143152 | Screenshot_20240328-143205 | Screenshot_20240328-143308 |

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          3 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>LargePlayerWidget</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>LargePlayerWidgetReceiver</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>PlayEpisodeAction</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — APPROVED** [review]
LGTM

**Comment by CookieyedCodes** [comment]
Could we have a bookmarks icon on the big & medium widgit?

**Comment by MiSikora** [comment]
Probably not. Bookmark is a paid feature and having a conditional support on a widget would be problematic.

**Comment by CookieyedCodes** [comment]
Fair point, maby a star or a next episode or chapter button then 🤔

**Pull request merged**
