### PR TITLE
Bookmarks - Update Tap to view bookmark notification action

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This makes adjustments to the `Tap to view` action on the `Bookmark added` notification to 
- display the bookmarks on the `Episode` screen instead of the player screen if the `PodcastEpisode` for which the bookmark was added  is not currently playing
- display the bookmarks for the `UserEpisode` if the `UserEpisode` for which the bookmark was added is not currently playing
- display bookmark not found message if the bookmark is deleted

Part of: https://github.com/Automattic/pocket-casts-android/issues/1595

#### Test.1 For currently playing episode

1. Go to `Profile` -> `Settings` -> `Headphone controls`
2. Tap `Next action`
3. Select `Add bookmark`
4. Play any podcast episode
5. Minimize the app
6. Double-tap the headphone to add a bookmark
7. Notice that `Bookmark added` notification is displayed
8. Tap on the notification to view the bookmark
9. ✅ Notice that the `Bookmarks` tab on the `Player` screen is shown 

#### Test.2 For podcast episode not currently playing

1. Continue from above
2. Repeat steps 4-7
3. Open the app and play any other podcast episode 
4. Tap on the notification to view the bookmark
5. ✅ Notice that `Bookmarks` tab on the `Episode Details` screen for the bookmark episode is shown

#### Test.3 For user episode not currently playing

1. Continue from above
2. Play any user episode
3. Repeat steps 5-7
4. Open the app and play any other podcast episode 
5. Tap on the notification to view the bookmark
6. ✅ Notice that `Bookmarks` screen for the bookmark user episode is shown

#### Test.4 Bookmark deleted

1. Continue from above
2. Repeat steps 4-7
4. Open the app and delete the newly added bookmark
5. Tap on the notification to view the bookmark
6. ✅ Notice that `Bookmark not found` snack bar message is shown

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- Any jetpack compose components I added or changed are covered by compose previews N/A
 
#### I have tested any UI changes...

- with different themes N/A
- with a landscape orientation N/A
- with the device set to have a large display and font size N/A
- for accessibility with TalkBack N/A

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mchowning — APPROVED** [review]
This looks good Ashita! I just noticed two issues when testing this.

### 1. Switching to the full-screen player's bookmark tab can be slow

While testing this on my new-ish, but quite low-powered Samsung device, I noticed that sometimes the app was very slow to switch to the bookmarks tab on the Full Screen player (i.e., it would freeze on the full-screen player for a few seconds second). It might just be that my device is that slow, but it was a bit jarring, so I think it would be good to see if there's any way to speed that up or get to the bookmarks tab more directly. FWIW, on my Pixel 6 Pro the delay seemed well within the acceptable range, so this is likely only an issue on slower devices. Here's a video of what it looked like for me.

https://github.com/Automattic/pocket-casts-android/assets/4656348/cd5f631b-4af3-4e3f-8b1a-46d2b5c54a76

### 2. Bookmarks notifications and bookmarks episode screen tabs don't provide much context

The notification for bookmarks don't give any context about what episode the bookmark was made on. This is not generally a problem since the episode is currently playing, but it becomes a bit more confusing when it is for a previously played episode like you had in the test steps for this PR.

If the episode is not playing and the bookmarks for the episode are loaded outside of the full-screen player (i.e., the file screen or the podcast episode screen), the situation still is unclear because the screen just says "Bookmarks" without indicating what episode/file the bookmarks are for. This is particularly tricky for files because backing out of the bookmarks screen just takes you back to the Profile screen, so it never shows which file the bookmark was for.

This is definitely not a blocker and more just some thoughts about potential future improvements.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
Thanks for all the testing and feedback!

> Switching to the full-screen player's bookmark tab can be slow

There's a 1-sec delay added [here](https://github.com/Automattic/pocket-casts-android/blob/main/app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt#L1470) to allow loading of the tabs, but in the video you provided I see ~6 secs delay. I can't think of a straightforward way to address it, but I'll keep this in mind.

> Bookmarks notifications and bookmarks episode screen tabs don't provide much context

This PR's scope is to point to the correct bookmarks screen even if the episode is not playing, but it is good feedback to address at some point.

**Pull request merged**
