### PR TITLE
Bookmarks: fixes

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This fixes below bookmarks issues:

- Updates "Add bookmarks" eligibility for headphone settings which was earlier restricted to only Patron
- Dismisses full screen player on tapping headphone settings button from no bookmarks view.  

## Testing Instructions

- Set versionName=`7.52-rc-1` in version.properties

####  Test.1 Save Headphone controls setting 

1. Install the build
2. Login as Plus user
3. Go to Profile -> Settings -> Headphone controls
4. Change Previous and Next actions to "Add bookmark"
5. Exit from the app
6. Reopen the app
7. Go to Headphone controls screen
8. ✅ Notice that Previous and Next actions are saved from the previous session

https://github.com/Automattic/pocket-casts-android/assets/1405144/5312a1a1-b841-4770-9727-46799264b8fb

####  Test.2 No bookmarks - Dismiss full screen player on tapping headphone settings

1. Install the build
2. Login as Plus user
3. Play an episode with no bookmarks and open full screen player
4. Navigate to Bookmarks tab
5. Tap Headphone settings
6.  ✅ Full screen player should dismiss and Headphone controls settings should be visible

https://github.com/Automattic/pocket-casts-android/assets/1405144/fbe1f090-996d-44d4-8b91-8883f62aa9b7

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/39">7.52</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/39">7.52</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/39">7.52</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/39">7.52</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
@emilylaguna this has been tested here: p1699879199445519-slack-C02A333D8LQ. Can I get your approval?

**Review by zwarm — APPROVED** [review]
@ashiagr - All works as expected. 👍

**Pull request merged**
