### PR TITLE
Add theme support for Up Next

### PR DESCRIPTION
**Pull request by mchowning**
## 1. Description
This adds theme support to the Up Next screen. Among other things, this will help make the app more accessible. There is a setting allowing users to override the theme and have the up next default to dark mode (like it is currently). By default, the up next continue to use the dark theme for existing users. New users will default to having the Up Next screen apply the same theme as the rest of the app.

I have not made any changes to how the multiselect checkboxes are handled—those are using the same theming behavior on the Up Next that is used everywhere else in the app that multiselect is possible.

iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/1265

The dark mode for up next is now slightly different from how the Up Next screen looked before because the Up Next screen was not actually using dark mode before but was instead essentially a manual implementation of a custom dark-like theme for the full-screen player and the Up Next queue. I tried to minimize the amount of custom changes we made to the themes on this screen, while still making sure that everything looked good across all the themes.

### 2.1 Dark mode is used for existing users
1. Do a fresh install of the app from `main`
2. Make sure the app is using a light theme (i.e., if your phone is in dark mode, you will need to update the theme)
3. Add some items to you up next
4. Observe that the up next queue is dark
5. Install the app built from this PR
6. Open the Up Next by tapping the Up Next icon on the miniplayer
7. ✅ Verify Up Next is using the dark theme
8. Dismiss the Up Next screen
9. Open the Full Screen player
10. Tap the Up Next icon at the top of the screen
11. ✅ Verify Up Next is using the dark theme
12. Dismiss the Up Next screen
13. Swipe up to show the Up Next screen
14. ✅ Verify Up Next is using the dark theme
15. Dismiss the player
16. Tap Profile > Cog > Appearance
17. Scroll down to the Up Next section
18. Disable the option for using the dark theme on Up Next
20. Open the Up Next
21. ✅ Verify the Up Next screen is now using your current theme

### 2.2. Current theme is used for new users
1. Launch the app in fresh install
2. Add some items to your up next
6. Open the Up Next by tapping the Up Next icon on the miniplayer
7. ✅ Verify Up Next is using the dark theme
8. Dismiss the Up Next screen
9. Open the Full Screen player
10. Tap the Up Next icon at the top of the screen
11. ✅ Verify Up Next is using the dark theme
12. Dismiss the Up Next screen
13. Swipe up to show the Up Next screen
14. ✅ Verify Up Next is using the dark theme
10. Tap Profile > Cog > Appearance
11. Scroll down to the Up Next section
12. Enable the option for using the dark theme on Up Next
13. Make sure the app is using a light theme
14. Open the Up Next
15. ✅ Verify Up Next is now using the dark theme even though the rest of the app has a light theme

### 2.3. Make sure each of the themes look good
1. Launch the app 
2. Disable the Use Dark Mode Setting
3. Play an episode so it's about half way but have no items in your up next
4. Open the Up Next
5. ✅ Verify all of the labels, and now playing progress are legible in each theme
6. Add some items to your up next
7. ✅ Verify all of the labels, icons, and colors are legible in each theme

### 2.4 Settings Analytics
1. Launch the app
13. Tap Appearance
14. Scroll down to the Up Next section
15. Toggle the option for using a dark up next theme
16. ✅ Verify you see: `🔵 Tracked: settings_appearance_use_dark_up_next_toggled, Properties: {"enabled": ENABLED, ...}` where ENABLED is the state of the switch

### 3.1. Empty Up Next Queue

| Light | Dark | Rosé | Indigo | Extra Dark |
| --- | --- | --- | --- | --- |
| Screenshot 2023-12-11 at 8 48 04 PM | Screenshot 2023-12-11 at 8 48 11 PM | Screenshot 2023-12-11 at 8 48 18 PM | Screenshot 2023-12-11 at 8 48 27 PM | Screenshot 2023-12-11 at 8 48 33 PM |

| Dark Contrast | Light Contrast | Electricity | Classic | Radioactivity |
| --- | --- | --- | --- | --- |
| Screenshot 2023-12-11 at 8 48 40 PM | Screenshot 2023-12-11 at 8 48 48 PM | Screenshot 2023-12-11 at 8 49 03 PM | Screenshot 2023-12-11 at 8 49 09 PM | Screenshot 2023-12-11 at 8 49 16 PM |

### 3.2 Full Up Next Queue

| Light | Dark | Rosé | Indigo | Extra Dark |
| --- | --- | --- | --- | --- |
| Screenshot 2023-12-11 at 8 27 52 PM | Screenshot 2023-12-11 at 8 28 02 PM | Screenshot 2023-12-11 at 8 28 17 PM | Screenshot 2023-12-11 at 8 28 27 PM | Screenshot 2023-12-11 at 8 28 33 PM |

 
| Dark Contrast | Light Contrast | Electricity | Classic | Radioactivity |
| --- | --- | --- | --- | --- |
| Screenshot 2023-12-11 at 8 28 39 PM | Screenshot 2023-12-11 at 8 28 47 PM | Screenshot 2023-12-11 at 8 28 54 PM | Screenshot 2023-12-11 at 8 29 00 PM | Screenshot 2023-12-11 at 8 29 06 PM |

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
This looks so good! 💟 

> The dark mode for up next is now slightly different from how the Up Next screen looked before because the Up Next screen was not actually using dark mode before but was instead essentially a manual implementation of a custom dark-like theme for the full-screen player and the Up Next queue.

I grabbed a before and after screenshot. They look almost the same except for the chevron color which in-fact looks better now.

Before | After
----|-----
live | current


 I also noticed iOS displaying sub-titles in different colors https://github.com/Automattic/pocket-casts-ios/pull/1265#issuecomment-1847583434.We might want to keep the same style on both platforms.

**Review by ashiagr — APPROVED** [review]

**Comment by mchowning** [comment]
> I also noticed iOS displaying sub-titles in different colors https://github.com/Automattic/pocket-casts-ios/pull/1265#issuecomment-1847583434 might want to keep the same style on both platforms.

I believe I'm already using the same theme value that iOS is using for those (`primaryText02`). The only theme that shows such a significantly different color for the `primaryText02` color is the Electricity theme, and this is what they look like on iOS and Android. On the other themes both iOS and Android are showing more neutral colors.

| iOS | Android |
| --- | --- |
|  |  |

**Comment by CookieyedCodes** [comment]
In my opinion, android looks better in this instance 😉

**Pull request merged**
