### PR TITLE
Implement Medium Player widget

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This targets a separate branch instead of `main` because widgets cannot be feature flagged as they are compile time dependent. Once all features are implement I will make a PR for the `task/widgets` branch.

Designs: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1044_7170

There are some known issues:

1. Sometimes artwork doesn't load and placeholder is displayed instead. Even though the `Image` composable receives a correct `ImageProvider` it still doesn't update. It might be a bug withing the `Glance` library. However image loads correctly once the playback is resumed.
2. Widget's preview and placeholder are currently not implemented. Internal ref: p1711476556931619/1711396714.667229-slack-C05RR9P9RAT

### Migration

1. Install the app from c7be31ea0c5222c40969a53de51b10afdcbac892.
2. Add the medium sized widget (the old one).
3. Add something to your queue so that the widget display something.
4. Install the app from `tsak/medium-widget`.
5. The widget should stay on screen but should use new design.

### Functionality

1. Test that app opens when nothing is in the queue and you tap on the widget.
2. Test that the app episode details when you tap on widget background or artwork while episodes are in queue.
3. Test that the playback start and stops when you tap on the on the play button.
4. Test that the playback skips backward and forward when tapping on control buttons.
5. Test that the widget respects `Use embedded RSS artwork`.
6. Test that the widget respects `Use dynamic colors for widget` and Dark/Light themes.
5. Test that the widget updates artwork when currently playing episode is changed.

### Dark and light mode

| Dark | Light |
| - | - |
| Screenshot_20240327-160953 | Screenshot_20240327-160944 |

### Dynamic themes

| A | B | C |
| - | - | - |
| Screenshot_20240327-160820 | Screenshot_20240327-160704 | Screenshot_20240327-160619 | 

| D | E | F |
| - | - | - |
| Screenshot_20240327-160517 | Screenshot_20240327-160532 | Screenshot_20240327-160557 | 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>MediumPlayerWidget</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>SkipBackAction</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>SkipForwardAction</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — CHANGES_REQUESTED** [review]
I am facing with an issue when I am doing the tests migration:

1. Install the app from https://github.com/Automattic/pocket-casts-android/commit/c7be31ea0c5222c40969a53de51b10afdcbac892
2. Add the old medium widget
3. I already had something in my queue before install the app
4. Install the app from this branch
5. The widget loading never stops


https://github.com/Automattic/pocket-casts-android/assets/42220351/703ad8f1-259c-40cf-9349-abd7f4aff968

**Comment by MiSikora** [comment]
I'm unable to replicate the issue. Can you check the logs for any errors related to widgets?

https://github.com/Automattic/pocket-casts-android/assets/30936061/f87d5a4f-1ad1-44b0-ba27-51037ae13c90

**Comment by mebarbosa** [comment]
> I'm unable to replicate the issue. The widget is updated around `00:30`. Can you check the logs for any errors related to widgets?
> 
>  screen-20240328-102554.mp4

The only error I am getting is this one:


image

Nothing related to widget. I will DM you on slack the full video. I am able to reproduce this 100%

**Review by mebarbosa — APPROVED** [review]
Sorry. I was using Android Studio build button for testing. 

Using `./gradlew :app:installDebug --rerun-tasks` worked pretty well

**Pull request merged**
