### PR TITLE
Fix/issue 1228 theme selection UI bug

### LINKED ISSUE #1228: Theme selection UI can incorrectly indicate currently selected theme
### Description

When using a free account, selecting a Plus "theme" can result in subsequently selected themes not reflecting the current state of the UI—the UI will have the just-selected theme active, but the UI will indicate that a previously selected theme is active.

This is related to https://github.com/Automattic/pocket-casts-android/issues/68

### Step-by-step reproduction instructions

1. With a Free account,
2. Go to "Profile" → ⚙️  → "Appearance"
3. Select a "Free" theme
4. ✅ Observe that the UI updates to that theme and indicates that theme is selected
5. Select a "Plus" theme
6. Dismiss the Plus promotion screen
7. 💥 Observe that the UI indicates that the Plus theme is selected, but the UI displays the previously selected theme
8. Select a "Free" theme
9. 💥 💥  Observe that the UI updates to the selected theme, but indicates that the previously selected Free theme is currently selected.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/4656348/f1d1c875-e47a-4289-918f-5fdb3b7434de

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung A13, Android 13, Pocket Casts 7.44 pre-release build

### PR DESCRIPTION
**Pull request by P-Burk**
## Description

This PR fixes an issue where when a user is not logged into a PC Plus account and selects a Plus theme, the UI will indicate the wrong theme as being selected once the user exits the Plus on boarding screen. Furthermore, the UI would scroll back to the "selected" theme even though that was not the actual active theme.

Fixes #1228

## Testing Instructions

1. With a Free account
2. Go to "Profile" → ⚙️ → "Appearance"
3. Select a "Free" theme
4. The app should update with the selected theme and the UI should indicate the selected theme.
5. Select a "Plus" theme
6. The on boarding screen should come up
7. Navigate back to the theme selection view
8. The app should be in the last selected "Free" theme and the UI should indicate that said theme is selected

#### Before:
Check the original issue for a Before screen cap of the issue.
#### After:
https://github.com/Automattic/pocket-casts-android/assets/68164093/ec5046ca-9311-4647-a480-e2679220e862

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
   - No strings added
- [ ] Any jetpack compose components I added or changed are covered by compose previews
   - No Jetpack compose components added or changed.
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

## Notes
I tested my changes without lines [126-127](https://github.com/P-Burk/pocket-casts-android/blob/6639c81f10be103486bf0738d3da9cdf81a8d197/modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt#L126) as well as with those two lines still in the code, and the bug fix performs as expected/desired either way (for me at least). I left these two lines in because I didn't want to delete something that I don't feel like I fully understand why it's there in the first place.

### CODE REVIEW

**Comment by P-Burk** [comment]
Also, how do I know which version in the CHANGELOG.md I should add a bug fix entry to? Do I just add it to the highest version in the file currently and then if it needs to be moved, one of the Automattic team members will do so?

**Comment by mchowning** [comment]
Thanks for the contribution, @P-Burk !

> Do I just add it to the highest version in the file currently and then if it needs to be moved, one of the Automattic team members will do so?

That's right, just put it on the newest version and if/when it needs to be moved either you or one of us will do that. 👍

**Comment by P-Burk** [comment]
> Thanks for the contribution, @P-Burk !
> 
> > Do I just add it to the highest version in the file currently and then if it needs to be moved, one of the Automattic team members will do so?
> 
> That's right, just put it on the newest version and if/when it needs to be moved either you or one of us can do that. 👍

Ok, good to go. I pulled the most recent changes to the main branch into my bug fix branch and added my bug fix note to the changelog file.

**Review by mchowning — APPROVED** [review]
These changes look great @P-Burk ! I just updated your branch with the latest changes from `main` and then moved the changelog entry to `7.49` since we cut `7.48` shortly after you opened this.

Thanks for contributing to Pocket Casts!

**Pull request merged**
