### PR TITLE
Add sleep timer by episode

### PR DESCRIPTION
**Pull request by DaveHurley7**
## Description
Adds into the sleep timer the feature of sleeping by episodes<br>
Changed the layout of the minute presets

## Testing Instructions
1. Begin any podcast episode
2. Open the miniplayer to expand it
3. Select the sleep timer icon in the icon list

## Screenshots or Screencast 
sleep-timer-episodes-screenshot4
sleep-timer-episodes-screenshot3
sleep-timer-episodes-screenshot2
sleep-timer-episodes-screenshot1

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
@DaveHurley7 Woop we finally got their 
Just noticed 2 small things 

1. "in" should be "after" because it is an after timer in our talks
2. It starts on "next" right?

**Comment by DaveHurley7** [comment]
Have updated the strings for 'end of' and 'end in' to now be 'end after'.
Here are the new screenshots I've taken:
updated_screenshot1
updated_screenshot2
updated_screenshot3
updated_screenshot4

**Review by MiSikora — CHANGES_REQUESTED** [review]
I'm unable to test the code. Project doesn't build due to wrong conflict resolution.

```sh
❯ ./gradlew :app:assembleDebugProd              

> Configure project :
e: file:///Users/mehow/Workspace/pc-timer/build.gradle.kts:15:31: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val ToolchainManagement.jvm: JvmToolchainManagement defined in org.gradle.kotlin.dsl
e: file:///Users/mehow/Workspace/pc-timer/build.gradle.kts:24:24: Unresolved reference: protobuf

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mehow/Workspace/pc-timer/build.gradle.kts' line: 15

* What went wrong:
Script compilation errors:

  Line 15:     alias(libs.plugins.kotlin.jvm) apply false
                                         ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                                             public val ToolchainManagement.jvm: JvmToolchainManagement defined in org.gradle.kotlin.dsl

  Line 24:     alias(libs.plugins.protobuf) apply false
                                  ^ Unresolved reference: protobuf

2 errors

```

I haven't reviewed the code logic yet. Comments that I left need to be addressed first.

There is also issue with the design. Please follow the design that were provided by us in [this discussion](https://github.com/Automattic/pocket-casts-android/discussions/503) unless it was aligned somewhere else.

292558584-f3038dce-5003-42ee-9a9c-dc2e7e2e9206

David mentioned this:

> We'd have to take a look at usage data and see if one of these is underused before feeling confident to make that decision.

I've checked our analytics and the least used one is the 5 minutes one.

**Comment by CookieyedCodes** [comment]
@MiSikora I got approval on this design don't worry 😁

**Comment by CookieyedCodes** [comment]
Regarding the comeing soon, this pr dosen't have to be merged until the other pr are done, it is only their as place holder 😉 so that you guys have an understanding what the UI will look like :)

**Comment by CookieyedCodes** [comment]
https://github.com/Automattic/pocket-casts-android/discussions/503#discussioncomment-8371473 link to the design I confirmed with your designer 5 days ago :)

**Comment by MiSikora** [comment]
> Regarding the comeing soon, this pr dosen't have to be merged until the other pr are done, it is only their as place holder 😉 so that you guys have an understanding what the UI will look like :)

Sorry but changes from external contributors need to be complete. Communication, project management, and code management is not as efficient as within the team.

> https://github.com/Automattic/pocket-casts-android/discussions/503#discussioncomment-8371473 link to the design I confirmed with your designer on slack 5 days ago :) -the dashed boxes were considered too much hence the removal-

Please don't take this the wrong way but I'll need a confirmation from David. @david-gonzalez-a8c can you confirm that this is the design we want to roll with for the sleep timer? Including using `mins`, `eps`, and so on?

302336609-707cbc10-2a78-47e7-9d14-6c89a6341516

**Comment by CookieyedCodes** [comment]
@MiSikora ya it's no bothers *bows* & no rush to merge, I have pushed my friend to focus on the preset manager and your fixes :), chapters will come as soon as my friend can figure it out 😅, if not sooner by you guys *bows*

**Comment by CookieyedCodes** [comment]
@MiSikora I have been giving it some thought regarding the language situation,
Mins in a brief search based off your supported languages is pretty universal it seems with one or two letter changes (inquiring with German currently & Japanese & Chinese is the same),
Chapters (chaps,) and episodes (eps) may be a bit more difficult but as the user is creating them it should be easier to communicate it to the user if the preset manager is using the full worlds.
(Agreed that the preset manager should say minutes then that was a slip up from me)

So we either its done through text or icons or less presets, I would find icons potentially less clear but I'll go off what @david-gonzalez-a8c agrees too 

Work is ongoing :), I'm gonna poke your designer on slack sometime this week if we're still in limbo :)

**Comment by CookieyedCodes** [comment]
A UI mockup considering your feedback @MiSikora, under this all 6 boxes would be customisable but the top 3 would default & filled to the recommended times, the bottom 3 would be blank, the chapter timer will be removed until its ready it is their to showcase its place, david gonzalez is busy currently so progress will be slow but I have kept him in the loop :),  Screenshot 2024-04-03 at 14 26 34

**Comment by mebarbosa** [comment]
Thank you, @DaveHurley7, for your hard work! We sincerely appreciate all that you do. Just wanted to inform you that we've begun working on our end to implement this feature

**Comment by CookieyedCodes** [comment]
@mebarbosa Coolio looking forward too it, were gonna work on some of my smaller niggles then:)

**Pull request closed without merging**
