### PR TITLE
Fix media notification controls configuration to support 3 icons

### LINKED ISSUE #590: Add support for new media notification controls configuration to support 3 icons (if room).
### Description

Recently the ability to [configure your media notification controls](https://github.com/Automattic/pocket-casts-android/pull/540) was added. Unfortunately, it changed the notification from three to two controls, so user's have mentioned they have lost the mark as played control.

We used to offer three controls, playback speed, star, and mark as played. The Android playback notification only shows two controls but Android Auto uses three controls. 

Before
Screenshot 2022-11-17 at 4 00 23 pm

After
Screenshot 2022-11-17 at 4 58 52 pm

It would be good to support three controls but it might be more difficult to implement the configuration page as we might want to let the user choose the positions so the user's least favourite control is removed.

### Step-by-step reproduction instructions

1. Follow the steps to set up an Android Auto emulator https://developer.android.com/training/cars/testing#test-auto
2. Deploy the app to a phone
3. Connect the phone using USB
4. Play an episode
5. Open the full screen playing screen

The mark as played control will be missing.

### PR DESCRIPTION
**Pull request by ksog66**
## Description
Add support for media notification controls configuration to support Maximum 3 icons.

Fixes #590 

## Testing Instructions
1. Setup Android Auto emulator https://developer.android.com/training/cars/testing#test-auto
2. Connect the phone using USB
3. Play An episode
4. Open full screen player on auto
5. Click on option (more vert) icon.
6. There will be 3 action displayed
7. Now you can prioritize this action
8. Go To Profile > Settings > General > Defaults.
9. Click on Media Notification controls under defaults setting.
10. Now drag and prioritize your preferred action from the following [ Archive, Mark As Played, Play Next, Playback Speed, Star] options.
11. There will be 2 action on Android 13 media notification player and 3 actions on android auto.

## Screenshots or Screencast 
media_action_light
media_action_dark
media_android_auto

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by ksog66** [comment]
Hey @ashiagr,This is working fine with android auto emulator right now, but I encountered a weird bug while testing on android auto emulator where, there were random icons shown instead of the media action, even for the forward and backward icons. even tough the functionality of the action were working as intended just the icons were different.

Couldn't reproduce it now, otherwise would attached a screen capture of that.
just wanted to know, if this bug is know?

**Comment by ashiagr** [comment]
👋 @ksog66!

Thank you so much for working on this! 

>  I encountered a weird bug while testing on android auto emulator where, there were random icons shown instead of the media action, even for the forward and backward icons. even tough the functionality of the action were working as intended just the icons were different.

I can't find any existing issue for it. And haven't been able to reproduce it so far. I'll let you know if I can reproduce it.

**Comment by ashiagr** [comment]
Look like wrong icons could be a DHU emulator thing and here's how you can get them right:
https://stackoverflow.com/a/71742689/193545

I'm still not able to reproduce wrong icons.

**Comment by ksog66** [comment]
Yes, i think it's an DHU emulator issue as I also encountered it when tested my changes for the first time on DHU emulator.
Even my problem solved only after following the same method provided in https://stackoverflow.com/a/71742689/193545 except the rebooting of my phone.

After that even i am not able to reproduce the issue.

**Comment by ashiagr** [comment]
Awesome work, @ksog66! 🥇 

I only have minor comments: 

1. Increase spacing between title and description by 8dp:

   Screenshot 2022-12-09 at 12 28 25 PM

2. Change titles slightly as follows:

   - `Your top actions will be available in your notification and Android Auto player` -> `Your top actions will be available in your Android 13 notification and Android Auto player`
   - `Other Media Action` ->  `Other media actions`

If you can address them now, I can prioritize and include this fix in 7.28.

**Comment by ksog66** [comment]
Made the changes. Please review it. also have updated the changelog and put in 7.8

**Pull request merged**
