### PR TITLE
Bump Tasker plugin

### LINKED ISSUE #2354: Tasker Integration broken in 7.66-rc-1
### Description

Using the Tasker integration is broken in the latest Beta Update.
All of Querying and Playing Episodes / Filters or Adding to Up Next does not work. There is no error being received either.
Pocket Casts has also crashed some times, while testing.

### Step-by-step reproduction instructions

(I am only using MacroDroid with the Tasker Plugin, so I can only give instructions for that.)
1. Create Macro
2. Add Action -> Applications -> Tasker/Locale Plugin -> Pocket Casts
3. Select Event Type (Querying / Playing / Adding to Up Next) for testing I used Playing Filter.
4. Select Filter
5. (Optionally add variable for error message)
6. Click on created Action
7. Test Action
8. Notice Pocket Casts does not start playing (and might crash)
9. (Notice error message variable stays empty)

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/72910336/403f4c0e-b605-449e-b97b-4726cd569206

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S23 FE
Android 14 OneUI 6.1
Pocket Casts 7.66-rc-1

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This updates Tasker plugin from 0.4.6 to 0.4.10

Fixes #2354

#### Test.1 MacroDroid
1. Login to Pocket Casts debugProd application with filters
2. Install and open MacroDroid application
3. Create Macro
4. Add `Action` -> `Applications` -> `Tasker/Locale Plugin `-> `Pocket Debug`
5. Select Event Type "Play Filters" for testing.
6. Select Filter
7. Click on the created Action
8. Test Action
9. ✅ Notice Pocket Casts starts playing filter episodes

## Screenshots or Screencast 

MacroDroid

https://github.com/Automattic/pocket-casts-android/assets/1405144/92e746dd-4895-4e05-bdda-43874e613230

#### Test.2 Tasker
(This test is optional. See the video for this test.)
1. Login to Pocket Casts debugProd application
2. Install and open Tasker application
3. Go to Tasks tab and create a task
4. Add `Action` -> `Pocket Debug` ->  `Pocket Casts Query Podcast Episodes`
5. Select configuration and choose a podcast
6. Tap OK
7. Go back to `Task Edit`
8. Add another action  `Pocket Casts Add to Up next`
9. Select configuration and choose %episode_uuid() in Episode IDs
10. Select Add Mode -> Current, Clear Before Adding -> Clear All, Start Playing -> True
11. Tap OK
12. Go back to `Task Edit`
13. Long press and select both the actions
14. Tap play at the bottom of the screen
15. ✅  Notice that episodes from selected podcasts are added to up next and start playing

Tasker

https://github.com/Automattic/pocket-casts-android/assets/1405144/014a55d6-3102-4c07-b8ad-35b0a527cfee

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
> ⚠️ 
> I could not execute query actions in MacroDroid, although I can from Tasker app. I could not run them even after changing target SDK version to 33. Maybe I'm missing something.


@b-aaron, can you install [app-7.65.apk]([app-7.65.apk](https://github.com/Automattic/pocket-casts-android/releases/download/7.65/app-7.65.apk)) from GitHub releases, and share a video showing querying `Pocket Casts Podcast Episodes` from `MacroDroid`?

**Comment by b-aaron** [comment]
@ashiagr 
Is there a way to downgrade the application without uninstalling it? I would preferably not have to delete all my downloaded files.

However, as to your question on how I query episodes, I noticed that you do not have any variables saved in MacroDroid, perhaps that's the problem?

Here's a video on how I would execute it, the only difference is that the variable 'ep_ids' does not get filled.
Also, I can confirm that this did work in 7.65, as I use this function quite regularly.

https://github.com/Automattic/pocket-casts-android/assets/72910336/91bce7bc-6c83-4613-b858-7d1c80259154

**Comment by ashiagr** [comment]
So I tested on 7.65 with a variable added for the action. I noticed that the variable is not populated if the app is not in the foreground. But it does otherwise:

https://github.com/Automattic/pocket-casts-android/assets/1405144/95021ca9-9a74-4569-b315-a9ba166e18f6

Do you remember anything like this?

**Comment by b-aaron** [comment]
That seems weird to me. I usually trigger my Macros with a Quick Settings Tile without having to start Pocket Casts first. I don't have any problems with that.

One thing that I should mention, is that I don't use `Query Podcast Episode` and instead use `Query Filter Episodes` for those Macros. I'm not sure whether that makes any difference though.

**Comment by mebarbosa** [comment]
> @mebarbosa can you too test querying podcast episodes or filter episodes on this branch and 7.65 for MacroDroid? It works for me for `Tasker` but not for `MacroDroid` if the PC app is not in the recent apps list.

@ashiagr It's working for me for both 7.65 and this branch. I tested it using Filter episodes

**Review by mebarbosa — APPROVED** [review]

**Comment by b-aaron** [comment]
I can confirm, that the Tasker Plugin is now functional again, in 7.66-rc-2. Thanks!

**Pull request merged**
