### PR TITLE
build: enable source context upload to Sentry

### PR DESCRIPTION
**Pull request by wzieba**
## Description

Sentry pushed to their SaaS our contribution (https://github.com/getsentry/rust-proguard/pull/36) which enables projects with R8 full mode to be correctly deobfuscated on Sentry dashboard.

So now it makes sense to send source context to their servers and benefit from more details when investigating issues on Sentry.

## Testing Instructions

Not needed: see screenshots below.

### Source context is uploaded:
image

### Sentry shows the source code around the stacktrace records

See: https://a8c.sentry.io/issues/5547984676/?project=6711064&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0&utc=true

image

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ParaskP7 — APPROVED** [review]
👋 @wzieba !

I have reviewed this PR and everything LGTM, good job! 🌟 

> Sentry pushed to their SaaS our contribution (https://github.com/getsentry/rust-proguard/pull/36) which enables projects with R8 full mode to be correctly deobfuscated on Sentry dashboard.

Awesome work there and congrats on this contribution of youors pushed into Sentry's Saas! 🎉 

> So now it makes sense to send source context to their servers and benefit from more details when investigating issues on Sentry.

👍 but what I don't understand is how to (kind of) test it. I know you said it is not needed, but I got curious and was trying to find a `release` issue on [Sentry](https://a8c.sentry.io/issues/?environment=release&project=6711064&referrer=sidebar&statsPeriod=90d) that would give me `SourceFile` instead of the correct name of the file.

Can you help point me to such issue? 🙏 

For example looking at [this](https://a8c.sentry.io/issues/4351877697/?environment=release&project=6711064&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0) issue I could see the correct name of the file already. I am more curious than anything else...

image

**Comment by wzieba** [comment]
Thanks @ParaskP7 for the reviews! Let me give you more context

> I got curious and was trying to find a release issue on [Sentry](https://a8c.sentry.io/issues/?environment=release&project=6711064&referrer=sidebar&statsPeriod=90d) that would give me SourceFile instead of the correct name of the file.

Because Sentry pushed the change to SaaS, you won't see `SourceFile` anymore - new and old events are now deobfuscated correctly on Sentry.

**Comment by ParaskP7** [comment]
> Because Sentry pushed the change to SaaS, you won't see SourceFile anymore - new and old events are now deobfuscated correctly on Sentry.

Thanks for the additional context here @wzieba , this is exactly what I was thinking as well, but then, my more targeted question is, why do we need to set the `includeSourceContext` then, that is, if it is anyway working already as expected, that's what I don't understand? 🤔

**Comment by wzieba** [comment]
> if it is anyway working already as expected, that's what I don't understand? 🤔

"it" here means "deobfuscation". Deobfuscation is now working correctly on Sentry and this is the result of Sentry enabling our contribution. This PR is not fixing deobfuscation.

> why do we need to set the includeSourceContext then

Because deobfuscation is now fixed, we're unblocked with sending source code to Sentry by setting `includeSourceContext` option.

I think examples can help here:

#### Stack trace with not correctly working deobfuscation and without source context
image

#### Stack trace with correctly working deobfuscation and without source context (before this PR)
image

#### Stack trace with correctly working deobfuscation and with source context (after this PR)
image

**Comment by ParaskP7** [comment]
Oh cool @wzieba , this helps a lot, thanks for providing examples to explain that to me, much appreciated! 🙇

**Pull request merged**
