### PR TITLE
Migrate LiveData To Coroutines Flow In Create Filter Screen

### PR DESCRIPTION
**Pull request by Mukuljangir372**
## Description
This PR includes migration of LiveData to Flow (Kotlin Coroutines) In Create Filter Screen.

## Testing Instructions
I've performed a sanity testing of filter screen
1. Create New Filter
2. View Created Filter
3. Apply Filter

## Checklist
- [X] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [X] I have considered whether it makes sense to add tests for my changes
- [X] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [X] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by Mukuljangir372** [comment]
@ashiagr Can you review this:)

**Review by ashiagr — CHANGES_REQUESTED** [review]
👋 

I briefly tested the changes and noticed an issue:

If I open an existing filter and tap menu options -> Filter settings then the application freezes

From main branch

https://github.com/Automattic/pocket-casts-android/assets/1405144/3b56fce6-71d5-4872-966a-259b91a56c58

From this branch

https://github.com/Automattic/pocket-casts-android/assets/1405144/7f7f2dea-6f7e-43f5-8085-bb489bcfe29c

Here are captured logs, in case they're helpful:

```
ANR in au.com.shiftyjelly.pocketcasts.debug (au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity)
                            PID: 30205
                            Reason: Input dispatching timed out (be57c9a PopupWindow:aeb8355 (server) is not responding. Waited 5006ms for MotionEvent)
                            Parent: au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity
                            ErrorId: 8ca8c404-6616-41a8-8cfd-7401e76d42ec
                            Frozen: false
                            Load: 0.17 / 0.47 / 0.29
```

**Comment by Mukuljangir372** [comment]
Thank you @ashiagr for your review and pointing out the issue. I've fixed the issue and pushed the changes. Issue was caused by blocking the main thread by using `runBlocking` in `onCreate` in `CreateFilterFragment`. I've migrated the `playlist` back to live-data because of flow doesn't allow blocking the streams. And this migration requires a lot of changes. I think we can skip this and do the migration in future for `playlist`.

**Comment by ashiagr** [comment]
LGTM. Thanks for the updates!

**Review by ashiagr — APPROVED** [review]

**Comment by ashiagr** [comment]
@Mukuljangir372 can you please resolve the conflict? I tried doing it but CI is complaining.

**Comment by ashiagr** [comment]
@Mukuljangir372 `license/cla` check is still pending. I see a few commits from @mukul-scogo `GitHub` username. Is it possible for you to sign CLA from that account?

Also /cc @iangmaia in case we're missing something.

**Pull request merged**
