### PR TITLE
Display RSS artwork in all possible places

### LINKED ISSUE #1608: Display episode artwork in more places in the app
In https://github.com/Automattic/pocket-casts-android/pull/1599 we added episode artwork to the full-screen player and the episode details screen, and we now want to use it in more places in the app. The current suggestion is to add it to the:

MiniPlayer | Bookmark row (Podcast screen) | Notification | Widget
---|----|---|---
miniplayer | bookmark | widget | widget1

@ashiagr  brought this up [here](https://github.com/Automattic/pocket-casts-android/pull/1599#pullrequestreview-1774364673), and @david-gonzalez-a8c shared his thoughts [here](https://github.com/Automattic/pocket-casts-android/pull/1599#issuecomment-1852267611). @b-aaron [said](https://github.com/Automattic/pocket-casts-android/pull/1599#issuecomment-1850851452) they would like to have a setting for whether to use the episode artwork in the notification.

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This PR redesigns how we create request for images. Previously we had `PodcastImageLoader` with multitude of different methods and it wasn't clear when to use which one. It was also hard extend this class to support handling different artworks. I removed that class and introduced `PocketCastImageRequestFactory` with a clearer and simpler API.

Episodes shown in the discovery feature do not show RSS artwork because server does not return image URL for episodes there.

Closes #1608 

## Testing Instructions

Test the screens that are using RSS artwork and see if they respect the `Use embedded RSS artwork` appearance setting. Also smoke test the rest of the app including user files, discovery, and any other place that you can think of.

### Android

| Episode | Up Next | Filters | 
| - | - | - |
| android-episode | android-up-next | android-filters |

| Downloads | Bookmarks | Widget |
| - | - | - |
| android-downlods | android-bookmarks | android-widget |

| Player | Mini player | Media notification |
| - | - | - |
| android-player | android-mini-player | android-notification-center |

| History | Starred |
| - | - |
| history | starred |

In theory notifications should use this as well but I'm not able to test it properly because our developer testing action clears the episodes which means that don't have image URLs when fetched.

### Wear OS

| Now Playing | Up Next | Filters | Downloads |
| - | - | - | - |
| wear-now-playing | wear-up-next | wear-filters | wear-downloads |

### Automotive

No changes to the automotive codebase and it still works as before. It is a bit finicky to test because there might be some delay due to image URL availability in episode entities.

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
Can we keep the upnext feed clear of RSS artwork 😅, mainly because to me it makes more sense that the upnext should be for sorting feed priority 😅

**Comment by MiSikora** [comment]
I don't have a strong opinion on it but single sample preferences aren't the best way to decide here. If enough people get upset we can always change it but for now I'd prefer to keep it.

**Comment by MiSikora** [comment]
@david-gonzalez-a8c Can you weigh in on whether we shouldn't support episode artwork on some of the screens? And if yes, in which ones?

**Comment by CookieyedCodes** [comment]
> I don't have a strong opinion on it but single sample preferences aren't the best way to decide here. For example @b-aaron wanted it https://github.com/Automattic/pocket-casts-android/pull/1599#issuecomment-1935826324. For my use case it also makes sense to use RSS artwork. If enough people get upset or let us know beforehand we can always change it but for now I'd prefer keeping it.

Ya understandable, I'm actually fine with it being everywhere but upnext, so maby an setting toggle spefically for upnext 🤔 🤔

**Comment by MiSikora** [comment]
> maby an setting toggle spefically for upnext

I'd prefer not showing RSS artwork at all in Up Next than having a separate setting. It's too specific and would go in the direction of turning our settings menu into a plane control panel. 😅

**Comment by david-gonzalez-a8c** [comment]
> @david-gonzalez-a8c Can you weigh in on whether we shouldn't support the episode artwork on some of the screens? And if yes, on which ones?

Besides the ones shown, I can think of:

- Starred
- Listening history
- Search results

I don't have a strong opinion, but I think listening history and starred might make sense and search results not so much. What do you think?

Also, it would be great coordinating this with a similar effort on iOS so we have parity.

**Comment by MiSikora** [comment]
> I don't have a strong opinion, but I think listening history and starred might make sense and search results not so much. What do you think?

Yes, starred and listening history are already handled. I forgot to add it in the PR description. Search uses podcast's artwork because we don't have episode URLs when browsing on that screen and I agree that it would be better to not use it there.

> Also, it would be great coordinating this with a similar effort on iOS so we have parity.

iOS right now doesn't support episode artwork at all because there were some memory issues. But I'll let the iOS folks know.

**Review by mebarbosa — CHANGES_REQUESTED** [review]
Great job!! As a user, I also prefer to display the RSS artwork

- I smoke-tested the app, and it worked pretty well. However, I noticed one thing related to our widget:
<details><summary>Widget test details</summary>

1. If I add the widget with the RSS artwork toggle OFF,
2. then turn the toggle ON,
3. the image in the widget is not updating, even after refreshing it. 

The only way to update it is by actually switching to another podcast
</details> 

- I also have a suggestion to add this to `Recent searches`:

<details><summary>Recent searches screenshot</summary>
<p>

Screenshot_20240315_092024


</p>
</details>

**Comment by MiSikora** [comment]
> Widget test details

Yes, I forgot to mentioned that. Right now it updates in a similar way to the notification center. You need to pause and resume an episode for the setting to take effect. Doesn't widget artwork refresh for you when you pause and play the episode? Changing that to be live would require far more drastic redesign of our widget handling and I'm not sure I want to introduce it in this PR.

> I also have a suggestion to add this to `Recent searches`:

As I mentioned it is not possible to have it in the Discovery page. Server doesn't provide the image URL there.

**Review by mebarbosa — APPROVED** [review]

**Comment by b-aaron** [comment]
Seeing this implemented now (which I am really enjoying), I really would love to be able to see all the episode covers within the main Episodes feed of a podcast. Can that be implemented as well?
I think it would be great, if there was a toggle within the podcast settings to show them, so that podcasts, which don't use custom episode covers show the same cover all over.

**Comment by CookieyedCodes** [comment]
One thing I'm getting concerned about with is the amount of custom artwork in the app is the amount of storage its going to take up on my device, can we get some controls for this & even a format that could compress the data even further 😅, I have nearly 2000 feeds & I want to cut down on photos that takeing up my storage 🤔

**Comment by MiSikora** [comment]
@b-aaron Can you create a feature request for that? It probably won't have a high priority but at least it will be tracked this way.

@CookieyedCodes Image cache size is limited.

**Comment by CookieyedCodes** [comment]
@MiSikora I assume it is, what's it set to artwork is like taking 6gbs 😅

**Comment by MiSikora** [comment]
It depends on a device and its storage state. But it is between 10MB and 250MB.

**Comment by CookieyedCodes** [comment]
Hmmmmm I don't know why my app says it's taking up 29Gb where's on google play is taking up 35Gb 🤔🤔

**Comment by CookieyedCodes** [comment]
I in fairness did assume it but my basis is somewhat in good grounding, when I had podcast addict as a pocketcasts backup 12 GBs out of 20glGBs taken by podcast addict of my phone at the time were being taken up with just artwork (no downloads, 5gbs were backups & the remainder was feeds I assume), I had about 1600+ feeds at time I think 

( if you think it's files 99.5% of my files I keep on my pocketcasts cloud so I have no idea what's taking up that missing 6 GBs 😅)

**Pull request merged**
