### PR TITLE
Custom Playback Settings: Add Feature Flag and add segmented tab bar

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This adds the `custom_playback_settings` Feature Flag and the segmented tab bar in the playback effects view.

** Ignore local files for now

Project #3042

## Testing Instructions

1. Play an episode and tap effects icon in full-screen player
2. ✅ Notice that the segmented tab bar is displayed at the top of the effects view** (hHFpI1RtnW4TRb448Q4Don-fi-4730_28640)
3. Disable the FF
4. Re-open the effects view and
5. ✅ Notice that the segmented tab bar is not displayed 
6. Go to Podcasts tab
7. Tap on locked folder icon
8. ✅ Notice that segmented bar on the Plans page looks fine

** Only match the segmented control in Figma, the top header is highlighted only on iOS.

## Screenshots or Screencast 

**Effects Settings**

**Plans**

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SegmentedTabBarColors</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires a [Type] label and either a [Area] or [Project] label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by geekygecko — COMMENTED** [review]
I have asked the design team about this change as I'm unsure if it's too much like an iOS control. It also feels quite a thin touch target. If it's ok with you I won't approve this until we have heard back from them.

Internal discussion pdeCcb-7bh-p2#comment-5776

**Comment by ashiagr** [comment]
@geekygecko 👋 

I've updated the component style and screenshots based on pdeCcb-7bh-p2#comment-5789. 
We might need a few tweaks from the designer so I've added a `do not merge` label.

**Review by geekygecko — APPROVED** [review]

**Comment by ashiagr** [comment]
As the feature is behind FF, I'm merging this PR. I'll revisit it once we have further updates: pdeCcb-7bh-p2#comment-5804

**Pull request merged**
