### PR TITLE
Make widget texts non scaling

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

Using scaling units for fonts on widgets isn't very practical since we don't have a good control over UI. This PR introduces `NonScalingText` widget UI element. It delegates to XML layout that is then embedded inside Glance. This allows us to control typical properties of TextView like text size which can now be expressed in `dp` instead of `sp`. Because of this change I had to do some workaround to enable proper theming on our texts. However, this also enabled changing alpha.

### Text size

1. Place medium and large widgets on the home screen.
2. Change system font to large or tiny size.
3. Text size on widgets should stay the same regardless of the system settings.
4. Test this with different queue combinations. Single episode, multiple episodes, no episodes.

### Text color

1. Place medium and large widgets on the home screen.
2. Have something in the queue.
3. Test if texts use correct colors based on dark/light mode and based on `Use dynamic colors for widget` setting. Try different combinations of those.

### Small widget

Smoke test small widget and if it looks correctly. There's been a small fix for playback button computation.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/51">7.62 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
Text sizes remain the same, but margins do not look right when the display size is increased: 

Small font | Large font
-----|-----
 | 

Can we do something about it?

**Comment by MiSikora** [comment]
Hmmm… I'm not sure. I'll poke around and see.

**Comment by MiSikora** [comment]
I think this is issue of widget not fitting described here: pdzxoO-oM-p2

I added one more fix though for playback controls clipping to the logo position when widget was scaled.

| Before | After |
| - | - |
| Screenshot_20240417-103110 | Screenshot_20240417-103358 |

**Comment by ashiagr** [comment]
> I think this is issue of widget not fitting described here - pdzxoO-oM-p2 - and you should be able to adjust the size of the widget.

It does look like a limitation. I'll go ahead and approve the PR.

**Pull request merged**
