### PR TITLE
Bookmarks - Add delete bookmark action in notification

### LINKED ISSUE #1595: Bookmark added notification feedback
When a `Bookmark added` notification is displayed, then
- on tapping the notification, display the bookmarks tab from the episode screen instead of the player screen 
- add an option to delete the bookmark from the notification

Feedback reported here:
https://pocketcastsbeta.slack.com/archives/C0GKY84CR/p1701786979207639
 

### Steps to get the `Bookmark added` notification

1. Open the app 
2. Login with a paid account
3. Go to `Profile` -> `Settings` -> `Headphones controls`
4. Enable `Add bookmark` for `Previous` or `Next` action
5. Connect headphones with support for `Previous` or `Next` action
6. Play an episode
7. Minimize the app
8. Double or triple-tap the headphone (based on whether the `Previous` or `Next` action is enabled above)
9. Notice that Bookmark added notification is displayed
10. Notice `Change title` option is displayed <----- Add an option to delete a bookmark from the bookmark
11. Tap to view the bookmark
12. Notice that it goes to the `Player` screen -> `Bookmarks` tab of the currently playing episode <----- Change this behavior to open the `Bookmarks` tab from the `Episode` screen for the episode for which the bookmark is added

### PR DESCRIPTION
**Pull request by ashiagr**
## Description

This adds a delete bookmark action in "Bookmark added" notification

Fixes #1595 

#### Test.1 Bookmark deleted
1. Go to `Profile` -> `Settings` -> `Headphone controls`
2. Tap `Next action`
3. Select `Add bookmark`
4. Play any podcast episode
5. Minimize the app
6. Double-tap the headphone to add a bookmark
7. Notice that `Bookmark added` notification is displayed
8. Tap `Delete` in the notification
9. ✅ Notice that bookmark is deleted and "Bookmark deleted" snackbar is displayed

#### Test.2 Bookmark not found
1. Continue from above
2. Repeat Test.1 steps 4-7
3. Open the app and delete the newly added bookmark
4. Tap `Delete` in the notification
5. ✅ Notice that "Bookmark not found" snackbar is displayed

#### Test.3 Change title when bookmark episode not playing
** I also used `bookmarkUuid` in the notification intent to load an existing bookmark while changing the bookmark title in https://github.com/Automattic/pocket-casts-android/pull/1617/commits/602ceae25e67a5171a977a599f334e08e609ced9

To test this change,
1. Continue from above
2. Repeat Test.1 steps 4-7
3. Open the app and play another episode 
4. Tap `Change title` in the notification
5. ✅ Notice that "Change bookmark title" screen is shown

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting) 
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- Any jetpack compose components I added or changed are covered by compose previews N/A
 
#### I have tested any UI changes...

- with different themes N/A
- with a landscape orientation N/A
- with the device set to have a large display and font size N/A
- for accessibility with TalkBack N/A

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mchowning — COMMENTED** [review]
Code changes look good, there are just a couple of things I think we might want to handle better.

After deleting a bookmark, the notification isn't removed. I was expecting the notification would be removed since I had interacted with it and deleted the bookmark. Maybe that's just me having an unusual expectation though since we did already have that behavior when tapping "Change title" on the notification.

If I delete the bookmark and go back to the notification, I can then click "Change title" and that pops open the screen for adding a new bookmark, which seems confusing to me.


https://github.com/Automattic/pocket-casts-android/assets/4656348/3c805dc5-16d1-4289-b8c0-75f3991f14b6

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
>  I was expecting the notification would be removed since I had interacted with it 

Addressed in https://github.com/Automattic/pocket-casts-android/pull/1617/commits/110ec1631824d6ca7624f900f5040699a601766a

> If I delete the bookmark and go back to the notification, I can then click "Change title" and that pops open the screen for adding a new bookmark, which seems confusing to me.

Addressed in https://github.com/Automattic/pocket-casts-android/pull/1617/commits/a05215cd8cc6e0726e73c2709717122ce784ad02


https://github.com/Automattic/pocket-casts-android/assets/1405144/5be8371d-80c0-4191-b9da-dae83bee80d9

This is ready for another look.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mchowning — APPROVED** [review]
The improvements are working great!

One small possible future improvement I noticed when testing this is that the snackbar message the notification triggers does not show if the full-screen player is open in the app. You have to dismiss the full-screen player to see the snackbar.

| Deleting a bookmark | changing the title of a deleted bookmark |
| --- | --- |
| <video width="350px" src="https://github.com/Automattic/pocket-casts-android/assets/4656348/9c307265-7489-48e9-a113-2975c0bcbaf3" /> | <video width="350px" src="https://github.com/Automattic/pocket-casts-android/assets/4656348/c2b0abde-dff8-4812-8623-2a24549488b3" /> |

**Pull request merged**
