### PR TITLE
Migrate account details to Compose UI

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This migrates the account detail sections to Compose UI. There is one UI difference—the switch is styled according to the theme and is vertically centered in the item. Theming is applied because handling it properly was cumbersome. Vertical centering is done because the base `Switch` component includes significant padding, and refactoring would be required to align it to the top.

## Testing Instructions

Verify these areas:
* Tapping on sections should use correct actions—including signing out, and deleting an account
* Theming
* Automotive

## Screenshots or Screencast 

Screenshot 2024-11-27 at 17 10 51

## Checklist
- [ ] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] ~I have considered whether it makes sense to add tests for my changes~
- [ ] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [ ] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
Looks good!

Could you check this one thing: 
I noticed that after changing the email, the new email is not reflected on the Account details screen:

https://github.com/user-attachments/assets/f6a05fad-fe38-4bf3-bc36-061c84569641

It was updated in the production version.

**Comment by MiSikora** [comment]
>  I noticed that after changing the email, the new email is not reflected on the Account details screen:

Fixed in https://github.com/Automattic/pocket-casts-android/pull/3295/commits/b230d7d7dd88e51ec6a146063a2916f5f393af46.

The issue was that email changes were not being observed, only the logged-in state. Previously, this worked because the collections in the profile and account detail pages were observed with the lifecycle. This caused the subscription to restart whenever a fragment was restarted. While I could have tried to follow the same approach here, but it would be harder in case of hot flows from view models. Also, it would not address the root cause and would rely somewhat on chance when observing the sign in state in the future.

There is, however, a potential risk that propagating email changes might cause unintended side effects. This is because `getSignInState()` is used in multiple places, and current observers might perform side-effect actions when it is triggered. That said, email changes are not a frequent action and are not triggered from many places, so I believe this approach is safe.

**Review by ashiagr — APPROVED** [review]
Works well now. 

> There is, however, a potential risk that propagating email changes might cause unintended side effects. This is because getSignInState() is used in multiple places, and current observers might perform side-effect actions when it is triggered. That said, email changes are not a frequent action and are not triggered from many places, so I believe this approach is safe.

I agree, it is not a frequent action so the solution looks safe to me too.

**Pull request merged**
