### PR TITLE
Integrate `measure-builds` plugin

### PR DESCRIPTION
**Pull request by wzieba**
## Description

This PR integrates [`measure-builds-gradle-plugin`](https://github.com/Automattic/measure-builds-gradle-plugin) to collect build metrics.

## Testing Instructions

1. Make sure you updated secrets (`bundle exec fastlane run configure_apply`), and you have `appsMetricsToken` value in `secret.properties`.
2. Run any task with `--debug` flag, e.g. `./gradlew help --debug`
3. Find `REQUEST: https://metrics.a8c-ci.services/api/grouped-metrics` log

Please mind that the connection **can time out** due to a backend issue. Please don't worry about it, it's a known issue that we'll address it later.

## Screenshots or Screencast 

 Screenshot 2023-12-11 at 12 47 48

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mchowning — APPROVED** [review]
This looks good @wzieba ! Thanks for adding it. I'm looking forward to seeing what insights this gains us.

Just some notes from my testing:
- Since we're enabling this in the secrets file, that means that anyone without the build secrets (like OS contributors) won't have their build times sent. This seems good. 👍 
- In light of that, I verified that the build works fine for users missing the `measure-builds` secrets
- I also verified that this doesn't cause any issues with builds when there are problems with the internet connection. It looks like the build-times don't get uploaded, but otherwise the build works fine.

**Comment by mchowning** [comment]
👋  @wzieba. I noticed that the build time also gets checked and submitted even when something minor like the Spotless linter in our pre-commit hook runs. Is there any chance that creates unnecessary noise in the data that is sent to the server or causes any other problems?

``` sh
▶ git commit

Running Spotless...

> Configure project :
Kotlin DSL property assignment is an incubating feature.

🐢 4 slowest tasks were:
Duration        % of build      Task
9s              70%             :spotlessKotlin
13ms            0%              :spotlessInternalRegisterDependencies
0ms             0%              :spotlessKotlinCheck
0ms             0%              :spotlessCheck

⏳ Reporting build data to Apps Metrics...

✅ Build time report of 0m 14s has been received by App Metrics.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 15s
3 actionable tasks: 3 executed

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

9:04PM INF scan completed in 59.8ms
9:04PM INF no leaks found
[update/theme-up-next f99b6ea15] Update changelog
 1 file changed, 7 insertions(+)
```

**Comment by wzieba** [comment]
Thank you for the insightful review @mchowning !

>  Is there any chance that creates unnecessary noise in the data that is sent to the server or causes any other problems?

Thanks for mentioning this. This shouldn't create any problems for Apps Metrics, but at the same, you make a good point that metrics for some tasks like linters might be unnecessary. I'll think about addressing this via some filtering mechanism, but I don't plan to do this right now (unless it's bothering the workflow, then please ping me, and I'll work on it right away!)

**Pull request merged**
