### PR TITLE
Referrals - Show welcome screen after user signed up and referral flow is complete

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This displays welcome screen after user signed up and referral flow is complete

## Testing Instructions

Prerequisites: 
- Release build
- Referrals FF enabled for release build
- License testing account
- Valid referral link

1. Install release build after enabling `Referrals` FF for release build
2. Open referral link
3. Notice that claim referral pass screen is shown
4. Tap `Activate my pass`
5. Sign up and complete purchase flow
6. Wait until the referral flow completes
7. ✅ Notice that the welcome screen is shown

## Screenshots or Screencast 

https://github.com/user-attachments/assets/c9ec7540-eda4-433e-b052-e8e5b3f89244

https://github.com/user-attachments/assets/c17270f7-95b7-454e-8b9c-5675e58e2a42

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires a [Type] label and either a [Area] or [Project] label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — APPROVED** [review]
It worked as expected. I have one question though. After claiming the referral I see `Next payment: <date>` under my account. Is this expected? I think it might be a bit confusing to the users who claimed a free referral.

Screenshot_20241011-101058

**Comment by ashiagr** [comment]
> After claiming the referral I see Next payment: <date> under my account. Is this expected? I think it might be a bit confusing to the users who claimed a free referral.

I think it is fine to display the next payment date. As you're testing it in a sandbox environment, you're seeing today's date. In a real world, a user will see the next payment date at a current date + 14 months. 

This is also conveyed in the claim pass screen message:
`Membership will automatically renew to a paid annual membership at $39.99 USD.`
(FVJPaWlRMlosEpsRhqxnSD-fi-2189_8613)

**Comment by ashiagr** [comment]
>  a user will see the next payment date at a current date + 14 months.

Sorry, I meant they'll see the next payment date at current date + 2 months.

**Pull request merged**
