### PR TITLE
[Playback skipping] Smooth transition from streaming to downloaded episode

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- As was reported [here](https://github.com/Automattic/pocket-casts-android/pull/1878#pullrequestreview-1900099251), the system to switch from streaming to downloaded episode was resulting in jumping a second or two back.
- This is caused by an random playback restart that we tracked here: https://github.com/Automattic/pocket-casts-android/issues/1509
- This PR removes the unnecessary playback restart for the caching episode case to implement a better transition between streaming and downloaded the episode.

> [!note]
> While you are testing, you might encounter the existing issue https://github.com/Automattic/pocket-casts-android/issues/86 related to the downloading percentage. I won't address it here as it's not within the scope of this task

> [!note]
> To test this PR I will to have the local `CACHE_PLAYING_EPISODE` feature flag enabled.

## Testing Instructions
- Repeat the tests described in https://github.com/Automattic/pocket-casts-android/pull/1878
- You can skip the `Charging Phone`, `Only on Unmetered WiFi` and `Automotive and Watch` tests if you wanted
- You should see a better transition after download finishes

## Screenshots or Screencast 
- See the video reported here when we were reseting the player for cached episodes: https://github.com/Automattic/pocket-casts-android/pull/1878#pullrequestreview-1900099251

After this improvement the transition will look like this:

[Screen_recording_20240227_135712.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/4fa23525-b4e3-4052-8e74-c365d5cb18b6)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Review by MiSikora — CHANGES_REQUESTED** [review]
While the jump is a bit smaller it is still noticeable and present.

Additionally there is a bug which I can't reproduce on `main`. When you select a different episode after the current one is downloaded it can jump back to playing the previous episode.

You can see both bugs in the video. The wrong episode playback is present around `00:15` and `00:35`.

https://github.com/Automattic/pocket-casts-android/assets/30936061/c6c79d34-6567-4742-b398-21725494840f

**Comment by mebarbosa** [comment]
> While the jump is a bit smaller it is still noticeable and present.
> 
> Additionally there is a bug which I can't reproduce on `main`. When you select a different episode after the current one is downloaded it can jump back to playing the previous episode.
> 
> You can see both bugs in the video. The wrong episode playback is present around `00:15` and `00:35`.
> 
>  video.mp4

Hey @MiSikora . I was able to remove the ~1 second jumps. You can check here: [d35260b](https://github.com/Automattic/pocket-casts-android/pull/1888/commits/d35260b7b976e3c0a612d57b8c0e75347c8902fa)

I was not able to reproduce this issue you reported but I believe this is related to switching episodes. Could you test it again?  [ed0281f](https://github.com/Automattic/pocket-casts-android/pull/1888/commits/ed0281fd61bdbaf5e50f1197c9efe366ea3fd725)

**Comment by MiSikora** [comment]
I can confirm that the jumping issue is gone. However the issue of switching episodes still persists.

And after the latest changes there is one more issue. The playback doesn't switch to the downloaded episode which if I assume correctly was the main counteraction to prevent skipping due to ads. It is downloaded and when I manually resume playback it starts from the file but it doesn't do it automatically. You can test it like with these steps.

1. Play an episode.
2. Let it download.
3. Disable Internet connection.
4. Seek to some timestamp in the episode.
5. Playback stops and you have to resume it manually.

https://github.com/Automattic/pocket-casts-android/assets/30936061/0c794351-beef-46a5-812c-656b9766fc2d

**Comment by mebarbosa** [comment]
Closing this PR since we decided to explore the Exoplayer cache option due these issues

**Pull request closed without merging**
