### PR TITLE
Onboarding Welcome Screen

### PR DESCRIPTION
**Pull request by mchowning**
| 📘 Project: #524  |
| --- |

## Description
Adding the welcome screen to the onboarding flow.

Note that the welcome screen does not include the card for importing podcasts because the import screens have not been completed yet.

## Testing Instructions

For all of these tests, make sure you turn on the onboarding feature flag in `base.gradle, and then complete these steps to load the welcome screen:
1. Open the app when not signed into an account
2. Tap "Sign Up"
3. Create an account
4. Tap "Not now" on the placeholder recommendations screen
5. ✅ Observe that the screens match the designs for both a Plus user and a free account user
6. ✅ Observe that the newsletter toggle is "on" by default

### 1. Discover something new

1. Tap on the "Discover something new" card
2. ✅ Observe that the main app screen is opened **to the Discover tab**
3. ✅ Go to the account screen and verify that the toggle state from the welcome page was persisted

### 2. Done

1. Tap on the "Done" button
2. ✅ Observe that the main app screen is opened
3. ✅ Go to the account screen and verify that the toggle state from the welcome page was persisted

### 3. Swipe back

1. Swipe back
2. ✅ Observe that a Plus user is taken back to the placeholder recommendations screen and a free user is taken back to the upgrade screen
3. Swipe back until you are taken back to the app's main screen
4. ✅ Go to the account screen and verify that the toggle state from the welcome page was persisted

### 4. Newsletter toggle removed from Create Account Page
1. Open the app when not logged in
5. Tap Create Account
7. ✅ Observe that there is not any option to change the newsletter (it moved from this screen to the welcome screen in this PR)

## Screenshots or Screencast 

| Free | Plus |
| --- | --- |
| image | image |

## Checklist
- [X] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] I have considered whether it makes sense to add tests for my changes
- [X] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [X] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [X] with different themes
- [X] with a landscape orientation
- [X] with the device set to have a large display and font size
- [X] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
Are emails still being sent out I haven't received one in over a year 🤔

**Comment by mchowning** [comment]
👋 @CookieyedCodes ! You're right, it has been a bit since we sent out an email.

**Review by ashiagr — APPROVED** [review]
Nice job, @mchowning! 

I just noticed a few design discrepancies:



Here's a patch with the changes in case it helps:
http://cloudup.com/cU81AbD07tj

Another minor thing I noticed is that OnboardingWelcomePage's preview complained of render issues: `Failed to instantiate a ViewModel. This preview uses a ViewModel.` 
Either we extract view content to another compose function or remove the preview section.

**Comment by mchowning** [comment]
Thanks for those design updates @ashiagr ! 🙇 I applied them in [3659ad5](https://github.com/Automattic/pocket-casts-android/pull/601/commits/3659ad52a08d478408fa589898f448e05fc894fc) and they look great.

The only change I made was to use `primaryText02` instead of `secondaryText02` for the card's description text ([405dc40](https://github.com/Automattic/pocket-casts-android/pull/601/commits/405dc4035b880c63818bfb273f5f1981cda6edd9)). The designs do call for the `secondarText02` color, but that color is for placeholders and is very hard to read in some of the themes. Our [color system documentation](https://docs.google.com/spreadsheets/d/1BZWwQo8ZhTt9jRz5eX6iJqt4r9o6ekWeYi_t8AlNDCM/edit#gid=1643906593)  says that `primaryText02` is meant for "secondary text" (does seem like our naming could be improved here), so I went with that instead of the `secondaryText02` in Figma. cc: @adamzelinski 

Here is what these two look like with the Indigo theme, for example:

| secondaryText02 | primaryText02 |
| --- | ---|
| image | image |

> Another minor thing I noticed is that OnboardingWelcomePage's preview complained of render issues: Failed to instantiate a ViewModel. This preview uses a ViewModel. Either we extract view content to another compose function or...

Great idea! I extracted another compose function in [a6b65f2](https://github.com/Automattic/pocket-casts-android/pull/601/commits/a6b65f2c8fa7010e8214632b7d2f3282c58dd986) and the previews for that function are working.

**Comment by adamzelinski** [comment]
Thanks for picking up on this one @mchowning I'll make sure to fix it in the design too. haha yeah, it can get a little confusing with the secondary and primary 2

**Pull request merged**
