### PR TITLE
Enable categories redesign feature flag by default

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- This is to avoid UI inconsistencies caused by delays in feature flag synchronization
- See: p1715062226510869-slack-C02A333D8LQ

## Testing Instructions
- Code review is enough.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Review by geekygecko — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/52">7.63 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mebarbosa** [comment]
@ashiagr @MiSikora `android_firebase_test ` is failing. Did you folks already saw this error before?

**Comment by MiSikora** [comment]
Did you check the test that is failing?

```xml
<testcase name="startDestination_PlusFlow_PlusUpsell" classname="au.com.shiftyjelly.pocketcasts.OnboardingFlowComposableTest" time="26.19">
  <failure>
    java.lang.IllegalStateException: Analytics flow not set at
    au.com.shiftyjelly.pocketcasts.account.onboarding.OnboardingActivity$onCreate$1.invoke(OnboardingActivity.kt:48) at
    au.com.shiftyjelly.pocketcasts.account.onboarding.OnboardingActivity$onCreate$1.invoke(OnboardingActivity.kt:38) at
    androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109) at
    androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35) at
    androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192) at
    androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556) at
    androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827) at
    androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314) at
    androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265) at
    androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940) at
    androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155) at
    androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127) at
    androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583) at
    androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551) at
    androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$1.invoke(TestMonotonicFrameClock.jvm.kt:104) at
    androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$1.invoke(TestMonotonicFrameClock.jvm.kt:103) at
    androidx.compose.ui.test.TestMonotonicFrameClock$performFrame$1.invoke(TestMonotonicFrameClock.jvm.kt:149) at
    androidx.compose.ui.test.TestMonotonicFrameClock$performFrame$1.invoke(TestMonotonicFrameClock.jvm.kt:132) at
    androidx.compose.ui.test.FrameDeferringContinuationInterceptor.runWithoutResumingCoroutines(FrameDeferringContinuationInterceptor.jvm.kt:60) at
    androidx.compose.ui.test.TestMonotonicFrameClock.performFrame(TestMonotonicFrameClock.jvm.kt:132) at
    androidx.compose.ui.test.TestMonotonicFrameClock.access$performFrame(TestMonotonicFrameClock.jvm.kt:53) at
    androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$2.invokeSuspend(TestMonotonicFrameClock.jvm.kt:110) at
    kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at
    kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231) at
    kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164) at
    kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466) at
    kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500) at
    kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489) at
    kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:587) at
    kotlinx.coroutines.test.CancellableContinuationRunnable.run(TestDispatcher.kt:60) at
    kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24) at
    kotlinx.coroutines.test.TestCoroutineScheduler.runCurrent(TestCoroutineScheduler.kt:132) at
    androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceDispatcher$1.invoke(AbstractMainTestClock.jvm.kt:74) at
    androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceDispatcher$1.invoke(AbstractMainTestClock.jvm.kt:67) at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33) at
    androidx.compose.ui.test.junit4.MainTestClockImpl$1.invoke(MainTestClockImpl.android.kt:32) at
    androidx.compose.ui.test.junit4.MainTestClockImpl$1.invoke(MainTestClockImpl.android.kt:32) at
    androidx.compose.ui.test.junit4.AbstractMainTestClock.advanceDispatcher(AbstractMainTestClock.jvm.kt:67) at
    androidx.compose.ui.test.junit4.AbstractMainTestClock.advanceTimeByFrame(AbstractMainTestClock.jvm.kt:38) at
    androidx.compose.ui.test.junit4.ComposeIdlingResource.isIdleNow(ComposeIdlingResource.android.kt:74) at
    androidx.compose.ui.test.junit4.IdlingResourceRegistry.areAllResourcesIdle(IdlingResourceRegistry.jvm.kt:124) at androidx.compose.ui.test.junit4.IdlingResourceRegistry.isIdleOrEnsurePolling$ui_test_junit4_release(IdlingResourceRegistry.jvm.kt:103) at
    androidx.compose.ui.test.junit4.EspressoLink.isIdleNow(EspressoLink.android.kt:44) at
    androidx.test.espresso.base.IdlingResourceRegistry.allResourcesAreIdle(IdlingResourceRegistry.java:4) at
    androidx.test.espresso.base.IdlingResourceRegistry$6.isIdleNow(IdlingResourceRegistry.java:1) at
    androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:10) at
    androidx.test.espresso.Espresso$1.run(Espresso.java:1) at
    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) at
    java.util.concurrent.FutureTask.run(FutureTask.java:266) at android.os.Handler.handleCallback(Handler.java:938) at
    android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at
    android.app.ActivityThread.main(ActivityThread.java:7656) at java.lang.reflect.Method.invoke(Native Method) at
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  </failure>
</testcase>
```

**Comment by MiSikora** [comment]
I retried the job. Previous failure was due to a different test so most likely it happened due to flakiness.

**Comment by mebarbosa** [comment]
> I retried the job. Previous failure was due to a different test so most likely it happened due to flakiness.

@MiSikora Finally they passed! I swear and I rerun a couple of times before tagging you 😓

**Pull request merged**
