### PR TITLE
replace useGoogleServicesDebugFile task with file in debug flavor

### PR DESCRIPTION
**Pull request by eighthave**
https://github.com/Automattic/pocket-casts-android/pull/1206#issuecomment-1743066565

## Description

Simplify build flavor setup so that we can introduce a "free" flavor https://github.com/Automattic/pocket-casts-android/pull/1206

Based on this suggestion:
https://github.com/Automattic/pocket-casts-android/pull/1206#issuecomment-1743066565

This could additionally include the same changes to the "wear" and "automotive" flavors.

## Testing Instructions

./gradlew build

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews

### CODE REVIEW

**Comment by mchowning** [comment]
Thanks @eighthave ! This looks good. 👍 

I pushed a few commits doing just a bit of housekeeping, and also extending this approach to the wear and automotive apps. Let me know if you have any thoughts about those updates.

Since I've pushed some non-trivial changes, let me also ask @geekygecko  and @ashiagr to take a look at this.

**Comment by eighthave** [comment]
LGTM!

**Comment by geekygecko** [comment]
> Since I've pushed some non-trivial changes, let me also ask @geekygecko and @ashiagr to take a look at this, particularly at the gitleaks change I made in https://github.com/Automattic/pocket-casts-android/commit/fed547e45d30469103f281e6f7dc744dd08e7152.

It looks good to me. Should we comment on what the entries in allowlist -> regexes are? It took me a little while to realise it was the Google Services API key.

**Comment by mchowning** [comment]
> Should we comment on what the entries in allowlist -> regexes are? It took me a little while to realise it was the Google Services API key.

Good idea @geekygecko . I added that in https://github.com/Automattic/pocket-casts-android/pull/1434/commits/95311e505af926434682068959de7f9f56ba1622.

**Review by geekygecko — APPROVED** [review]

**Pull request merged**
