### PR TITLE
Merge/release 7.54 into main

### PR DESCRIPTION
**Pull request by ashiagr**
Includes changes from #1643, #1647, #1665 + translations.

### CODE REVIEW

**Review by MiSikora — APPROVED** [review]
LGTM

**Comment by ashiagr** [comment]
Fixed a merge conflict here: https://github.com/Automattic/pocket-casts-android/pull/1670/commits/3cdfe998d5f518cb0b4e703c0546e928a9097ab2

**Comment by MiSikora** [comment]
Is the fix in 3cdfe998d5f518cb0b4e703c0546e928a9097ab2 correct? The PR with changes fixing playback speed display has a bit different code.

Original PR:

https://github.com/Automattic/pocket-casts-android/blob/e246ade544c2403e3263349b84fcb1d9404a331a/wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt#L48-L52

This PR:

https://github.com/Automattic/pocket-casts-android/blob/3cdfe998d5f518cb0b4e703c0546e928a9097ab2/wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt#L51-L56

**Review by MiSikora — COMMENTED** [review]
I can swear I've seen the conflict got resolved before my approval because I was specifically waiting for it beforehand. In any case LGTM 👍.

**Comment by ashiagr** [comment]
There was a merge conflict between https://github.com/Automattic/pocket-casts-android/pull/1643 from release/7.54 and recently merged: https://github.com/Automattic/pocket-casts-android/pull/1666 in `EffectsViewModel` that rounds playback speed.

The merge that you saw earlier was not correct around this part, it tried to directly change playback speed which is immutable val instead of var earlier.
image

Thanks for rechecking!

**Pull request merged**
