### PR TITLE
Fix for keyboard popup on episode preview close. Check if searchterm …

### PR DESCRIPTION
**Pull request by baruma**
…value is empty to determine hide/show keyboard.

## Description

Created fix for Issue #862.  Able to go back to search results without triggering keyboard to open.  Only files changed : SearchFragment.

Fixes # 
Issue #862 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Review by mchowning — APPROVED** [review]
Thanks so much for contributing @baruma ! 🙇 

In testing this, I see that the keyboard is no longer shown after tapping on an episode result! The keyboard does still get presented after returning from opening a podcast search result if the text field is active and after returning from opening a saved episode search result. 

Here are a couple of tables with what I found regarding whether the keyboard is shown or hidden after returning from opening a particular kind of result:

| Tapping on podcast...                           | Before this PR | After this PR |
| ----------------------------------------------- | ------ | ------ |
| result with text field active                   | shows | 🔴  shows  |
| result with text NOT active                     | hidden | hidden |
| saved search result with text field active      | shows  | 👍 hidden |
| saved search result with text field NOT active  | hidden | hidden |



| Tapping on episode...                             | Before this PR | After this PR  |
|-------------------------------------------------- |------- | ------ |
| ...result with text field active                  | shows  | 👍 hidden |
| ...result with text field NOT active              | shows  | 👍  hidden |
| ...saved search result with text field active     | shows  | 🔴 shows  |
| ...saved search result with text field NOT active | shows  | 🔴  shows  |


<details>
<summary>Video of cases where the keyboard is still being opened</summary>

https://user-images.githubusercontent.com/4656348/229886873-dafdb169-64c0-4ccf-85a0-cd35de68d717.mov

</details>

I think we want to also not have the keyboard shown in the 🔴  scenarios above, but that doesn't need to be fixed in this PR since your changes are a nice improvement (and address the specific issue identified in #862). 

I updated the PR to fix the formatting violation, and once I figure out why CLAssistant is upset with me I'll get this merged. Thanks again for contributing to Pocket Casts!

**Comment by mchowning** [comment]
>  once I figure out why CLAssistant is upset with me I'll get this merged

Actually it looks like you may have not signed the CLA yet. I assumed I was somehow the problem because the CLAssistant message didn't get triggered until I added my commit, but maybe it just didn't get triggered on your initial commit for some reason. 🤷  Let me know when you've signed the CLA, and if there are any more issues I'll look into it.

**Comment by baruma** [comment]
Thanks for letting me know, Matt.  Signed the License Agreement just now
and I'll look into resolving the keyboard bug on returning from the podcast
search.  Looking forward to helping out more.

Best,

Liana

**Comment by mchowning** [comment]
>  I'll look into resolving the keyboard bug on returning from the podcast search

Great! I'll go ahead and merge this PR since it's already a nice improvement. We can do any additional fixes in a separate PR.

**Pull request merged**
