### PR TITLE
Update Compose and other libraries

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This updates Compose to `1.6.1`through BOM and Compose compiler to `1.5.9`. The other updates are to follow the Compose update.

* Kotlin `1.9.22`
* KSP `1.9.22-1.0.17`
* Coroutines `1.7.3`
* Horologist `0.5.21`
* Wear Compose `1.3.0`
* Media `1.2.1`
* Coil `2.5.0`
* Lottie `6.3.0`
* Removed Accompanist because we used only deprecated APIs.

I probably could update other libraries which were transitively updated anyway but I wanted to stick to the core of the Compose ecosystem.

We still have one major migration to do, which is related to Wear Compose. `WearNavScaffold` and all of the related classes got deprecated. Fixing it is too much work for this PR in my opinion and each screen should be handled separately if possible to make testing easier. I suppressed deprecation in 79c04f852b1b502ae22426ff2d12e907f5a8ec50.

## Testing Instructions

1. Smoke test core features in `:app`, `:automotive`, and `:wear`.
2. Test the onboarding flow with theming due to changes in 2a9c637ed65f83d49f828f7e27f55c4386226617. #656 is a good reference PR
3. Test audio playback on Wear due to changes in cb5c02ea34d4ba6d121245285c42c141a4226d04. Matt mentioned some issues in the past https://github.com/Automattic/pocket-casts-android/pull/1634#issuecomment-1867226987 but I wasn't able to replicate.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ashiagr** [comment]
> Test audio playback on Wear 

I see a change of behavior now as compared to before where Bluetooth speakers were shown if none was connected to the watch (https://github.com/Automattic/pocket-casts-android/issues/1107#issuecomment-1663809781). Now, the sound comes through watch speakers. 

Before

https://github.com/Automattic/pocket-casts-android/assets/1405144/a6566fdc-b86a-4c2f-ba44-5d8e0be65d04

After 

https://github.com/Automattic/pocket-casts-android/assets/1405144/8b55ae53-69d0-495a-b808-d71a408f5fb0

I'll continue to test other scenarios and report back if I come across any regression.

**Comment by ashiagr** [comment]
I smoke-tested 

- phone app: authentication, onboarding, downloading,  refresh, opml import/ export, playback, notifications, upnext, widget
- automotive app: authentication, playback, skipping, refresh

and found no issues.

I'm still testing the Wear OS app, I'm hoping to complete it by tomorrow. Meanwhile, we need to fix the changed behavior reported in the previous comment.

**Comment by MiSikora** [comment]
> I'm still testing the Wear OS app, I'm hoping to complete it by tomorrow. Meanwhile, we need to fix the changed behavior reported in the previous comment.

I'm leaving for now for two reasons.

1. I think it will be better to fix it after we're done with testing Wear OS so other potential bugs are fixed as well.
2. It might be an option not to fix it at all since some users want such a behavior. I'll ask internally whether we should keep it as is or not.

And thanks for testing all of this. I know it's quite a bit.

**Comment by MiSikora** [comment]
Ok, we want to keep the previous behaviour. Internal ref: p1708955810276969-slack-C0290KZU508

**Comment by ashiagr** [comment]
> I'm still testing the Wear OS app

Other features in the Wear OS app are working well in my testing. We can merge the PR after we return to the previous behavior directing sound to Bluetooth speakers.

**Comment by MiSikora** [comment]
Ok, I might need to wait until I have a physical Wear OS device. I'll take a look at it today and decide depending on how complicated bringing it back might be.

**Comment by MiSikora** [comment]
afb9a69e67974ce1755b83a551c102fc58d332fb should bring back the same playback rules that we had before (both for emulator and for a real device). The class `PlaybackRules` was removed from the library and is now replaced with a simple `is` check.

**Comment by MiSikora** [comment]
I think 619920adfb7365e5fb5eb77acf8f15723b9af1ca should finally fix the issue of flaky tests due to coroutines machinery.

**Review by ashiagr — APPROVED** [review]
Everything works well in my testing. Great job!

**Pull request merged**
