### PR TITLE
Playback 2023 - Top five podcasts story

### PR DESCRIPTION
**Pull request by ashiagr**
| 📘 Part of: #1463 | 🎨 Designs: lH66LwxxgG8btQ8NrM0ldx-fi-1599_20385 |
|:---:|:---:|

## Description
Adds the 2023 visual for the Top Podcasts Story.

## Testing Instructions
1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile
3. Tap the EOY image
4. Skip to the fourth story
5. ✅ Check that the story looks good
6. Share this story
7. ✅ The story image should look good

## Screenshots or Screencast 

Pixel 7 
|-----|
|  |

Nexus 9 Tablet
|-----|
|  | 

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [ ] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
Still think it should be more then a top 5 😅

**Review by mchowning — APPROVED** [review]
This looks good. The only minor issue I saw is that the background highlight effect seems a bit light and might make it more difficult for some people to read the subtitle text since there's not much contrast. Not a blocker though.

image

**Comment by ashiagr** [comment]
> Still think it should be more then a top 5 😅

Thanks for the suggestion, @CookieyedCodes! It has been communicated to the team. While it might be difficult to fit 10-15 top podcasts on this screen, we're considering showing them in the Stats section.

**Comment by ashiagr** [comment]
> This looks good. The only minor issue I saw is that the background highlight effect seems a bit light and might make it more difficult for some people to read the subtitle text since there's not much contrast. Not a blocker though.

I realized that in my next PR where I rotated the blurred image (https://github.com/Automattic/pocket-casts-android/pull/1482/commits/037f0683131f1c079eedaa46bbe055d9cc474d1c) to get more contrast behind the text. I'll update the background for this story as well there.

**Comment by CookieyedCodes** [comment]
@ashiagr fair enough, I only request it because your podcast theamed end of year should be better then Spotifys 😅, more stats would allways be welcome 😁

**Pull request merged**
