### PR TITLE
Add Media Notification Controls for Android 13

### PR DESCRIPTION
**Pull request by ksog66**
## Description
Adding Media Notification Control setting under Defaults of General setting page, which gives Android 13 users option to have at max 2 option from Archive, Mark as played, Play next, Playback speed and Star option in notification media session.

## Screenshots or Screencast 
[clip4.webm](https://user-images.githubusercontent.com/70816971/198891544-8c27937e-51bb-4fb7-b301-8f190bd8e3f7.webm)
[clip1.webm](https://user-images.githubusercontent.com/70816971/198891557-5d97536a-8791-4d6f-a233-be4b10d05aaf.webm)
[clip2.webm](https://user-images.githubusercontent.com/70816971/198891564-14464ed7-eeac-4877-ace3-1533005adce8.webm)
[clip3.webm](https://user-images.githubusercontent.com/70816971/198891575-2355f27e-21b3-44ea-bc97-a506a1631544.webm)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by ksog66** [comment]
Hey @mchowning, I have added the implementation for issue #499 , but there is a issue am facing which is when the user update the media notification control setting while the media is in session in notification, the controls don't update instantly until there is an change in playbackstate.

**Comment by ashiagr** [comment]
Thank you so much for this PR, @ksog66! 🎉 

While we review the changes, can you run  `./gradlew :spotlessApply` on the root folder, it seems spotless has detected few formatting issues. I also triggered CI but you might not be able to see those CI issues.

It might also be nice to check why individual commits are showing after merging the `main` branch. Don't worry if you can't figure it out, we should be able to help. 🙂

**Comment by ksog66** [comment]
Hey @ashiagr, I ran the `./gradlew :spotlessApply ` command and found the error and fixed it and again ran and the build was successful.
And as for why individual commit by other contributor are there? I am not sure about it, but I tried squashing my commits into one commit and to do so, have synced original repos main branch with my local branch on which I was working and there were other contributors commits between my commits.

**Comment by ksog66** [comment]
Hey @ashiagr, should I push the fix of the issue which was failing this command `./gradlew :spotlessApply`?

**Comment by ksog66** [comment]
@ashiagr, should I squash the new commit also?

**Comment by ashiagr** [comment]
> should I squash the new commit also?

I'm assuming you're talking about [this commit](https://github.com/Automattic/pocket-casts-android/pull/515#issuecomment-1302023957), then yes. 

You can also follow the instructions from [here](https://stackoverflow.com/a/3903835/193545) or [here](https://docs.github.com/en/get-started/using-git/getting-changes-from-a-remote-repository) to pull and merge latest changes from the forked repo.

**Pull request closed without merging**
