### PR TITLE
Display Top 5 Shows Story

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This adds top 5 shows story.

Figma: lH66LwxxgG8btQ8NrM0ldx-fi-3054_3698

The behavior on small devices isn't specified. I opted for scrolling list with faded edges.

## Testing Instructions

1. Sign in with an account that listened to at least 5 minutes of episodes this year.
2. Sync your profile data.
3. Close the app.
4. Reopen the app.
5. Open Playback 2024.
6. You might see a loading progress bar and it might take some time to sync your data.
7. Once data is synced go to the top 5 shows story and verify it.

### Preview

Screenshot_20241016-113827

### Small device

https://github.com/user-attachments/assets/496f2cdf-cbd6-4d31-a997-79c9a1847cbf

### Animation

https://github.com/user-attachments/assets/635f3f64-ef28-411d-a0be-ee76bda3b33f

## Checklist
- [x] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] ~I have considered whether it makes sense to add tests for my changes~
- [x] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] ~for accessibility with TalkBack~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — APPROVED** [review]
I liked the scrolling list with faded edges! 

I have one suggestion/comment. I'm not sure if we've already discussed this, but do you think we could increase the time the list stays on the screen before it disappears and the animation starts again? 

In my experience, I think it was too fast

Great implementation!

**Comment by MiSikora** [comment]
Thanks! I'll ask David about it. I didn't have specification so I had to eyeball the duration.

**Comment by CookieyedCodes** [comment]
Still kind of would prefer a top 10 tbh 😅, I listen to so many podcasts 😅

**Pull request merged**
