### PR TITLE
Display clip sharing page

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This PR adds dummy view for clip sharing. There are some other things going on as well.

Designs: [Figma](https://www.figma.com/design/HR2vcQrWcS0scsolKZBitg/Sharing?node-id=2203-3602&t=xqZqxm81xipUz95T-4)

* fadba74789f8c763f625361b49381022eca95401 was done to prevent image composable pushing all content vertically.
* e4d23488877fe8ee3e8fc2b38997a8a5ca2d140b was done to prevent displaying placeholder which caused ugly blinking. Blinking still happens as we load episode cover but it is less aggressive.
* In 0bd3031df4e56c6d03c6f47c0af954d8210689a2 I had to introduce `ShareDialogFactory` to decouple sharing dialog from clip sharing fragment and still allow the fragment to be accessible from the dialog.
* Landscape mode is not implemented. Internal ref: p1718811037370009-slack-C05RR9P9RAT

### Regressions

1. Smoke test if artworks for episodes and bookmarks is still displayed correctly.
2. Smoke test if you can use previously available share actions.

### Feature

1. Play a podcast episode.
2. Tap on share action in the player's shelf.
3. Select `Clip`.
4. You should see clip sharing screen that is themed for a podcast.
5. Go to episode details (not in player).
6. Tap on share action.
7. Select `Clip`.
8. You should see clip sharing screen that is themed for a podcast.

## Screenshots or Screencast 

| Normal device | Small device |
| - | - |
| Screenshot_20240619-172342 | Screenshot_20240619_172319 |

| A | B | C | D | E |
| - | - | - | - | - |
| Screenshot_20240619-172517 | Screenshot_20240619-172504 | Screenshot_20240619-172415 | Screenshot_20240619-172358 | Screenshot_20240619-172342 |

## Checklist
- [x] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] ~with a landscape orientation~
- [x] with the device set to have a large display and font size
- [x] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          5 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Args</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ShareClipViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>UiState</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ShareDialogFactory</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mebarbosa — COMMENTED** [review]
Two minor things:

1. I think the `Create clip` label in figma is not aligned in the same horizontal line that X (close button)
2. The Clip button has no background color for this episode. Not sure if we will need to handle for all episodes

Screenshot_20240619_134722

**Review by mebarbosa — APPROVED** [review]
The feature looks good to me 👌🏽 

In my regression tests I noticed something. but I am not sure if this is a bug or not. Does the share current position option supposed to open the episode in the same position when the link was created? 

I can't open the episode set to some position. I am approving this PR, because I can reproduce this in `main` branch. I think this was working before 🤔

**Comment by MiSikora** [comment]
> I can't open the episode set to some position.

I can replicate the issue as well. I'll add it to the issue tracker and/or fix it later.

**Pull request merged**
