### PR TITLE
Transcripts - Update html format transcript display 

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
This fixes a few html format transcript display as follows:
1. Loads them in web view if they contain javascript
2. Replace apostrophe and quote using regx

Internal Ref: p1726671990578069-slack-C078746V6UX

## Testing Instructions
1. Install the app from this branch
2. Open the feeds mentioned below
3. ✅ Notice that the corresponding pages are loaded as described 

## Screenshots or Screencast 
----

I've had it
feed: https://www.podcastone.com/podcast?categoryID2=2332
Loads page in webview, search icon is hidden

----

TWit 
feed: https://feeds.twit.tv/sn.xml
This opens the HTML in the browser. 

----

Brain Science
feed: https://changelog.com/brainscience/feed
Replaces `&#39;` and `&quot;` with apostrophe and ".

----

If books could kill 
feed: https://feeds.buzzsprout.com/2040953.rss
Continue to be shown as before.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md [To be added]
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>do not merge</code> label(s).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires a [Type] label and either a [Area] or [Project] label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — COMMENTED** [review]
Overall looks good. I found a couple of issues with the browser.

1. When coming back from a browser the apps shows a blank transcripts screen.
2. Once the transcript is loaded in a browser they don't re-open when tapping on the transcripts screen. Instead a blank transcripts screen opens.

https://github.com/user-attachments/assets/668462be-935d-4e44-b8cf-97230b373ca4

**Comment by ashiagr** [comment]
Can you retry loading transcript for TWit feed: https://feeds.twit.tv/sn.xml?
Note that I've kept javascript disabled as it can introduce XSS vulnerabilities. I think it should be ok as the webview is used for transcript viewing.  

I also replaced HTML entities to [match with iOS](https://github.com/Automattic/pocket-casts-ios/pull/2192) in 2695c16.

**Review by MiSikora — APPROVED** [review]
I'm now experiencing a bit of a different issue. I need to use back button multiple times to close the web view. Typically two times. But, for example, if I close the transcripts page with the close button and then reopen it I need to use back button 3 times. I'm fine with moving forward with it if you think it would take too much time fixing it or if the root cause is unclear.

https://github.com/user-attachments/assets/861a7a9e-289a-4f1c-9db4-efe01999e31d

**Comment by ashiagr** [comment]
It depends on the web view load history.

For e.g. this feed (https://www.podcastone.com/podcast?categoryID2=2332) loads without a possible redirect and you can go back with a single swipe gesture. 

[Screen_recording_20240924_171831.webm](https://github.com/user-attachments/assets/c3cdfb52-ae55-4daa-9d71-40b59605c396)

TWit feed: https://feeds.twit.tv/sn.xml seems to be a special one. I think we can keep it this way. I may come up with another PR if I have a better solution to this.

**Comment by ashiagr** [comment]
Alright, I improved back handling in [f672310](https://github.com/Automattic/pocket-casts-android/pull/2910/commits/f672310f68efdd26ec5b9cd280be50fe2803eb00), hopefully, we can merge it now. 😅 

[Screen_recording_20240924_180418.webm](https://github.com/user-attachments/assets/3bf49de9-4ef6-4975-9482-fc09eaafe29d)

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — APPROVED** [review]

**Comment by ashiagr** [comment]
While we monitor analytics for web-page-based HTML transcripts (p1727414037079919-slack-C078746V6UX), I'm merging this PR that improves the existing display. I'll revisit it once we have further updates.
 

/cc @SergioEstevao, @david-gonzalez-a8c

**Pull request merged**
