### PR TITLE
Transcript - Transition from player screen

### PR DESCRIPTION
**Pull request by ashiagr**
## Description
When the transcript shelf item is clicked, a blank transcript screen opens with an animation.

** I've tried to match [animation on iOS](https://github.com/Automattic/pocket-casts-ios/pull/1899).

## Testing Instructions
1. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
2. Open full screen player
3. Tap on the Transcript shelf icon
4. ✅ Notice that a blank Transcript screen is shown with a transition, player controls are shown at the bottom
5. Drag up on the Transcript screen
6. ✅ Notice that the up next screen is not shown
7. Tap on the close button on Transcript screen
8. ✅ Notice that Transcript screen is closed
9. Drag up on the Player screen
10. ✅ Notice that the up next screen is shown

## Screenshots or Screencast 

Portrait - Phone

https://github.com/user-attachments/assets/62ee69ea-3406-4441-8470-5919b6a3999b

Landscape - Phone

https://github.com/user-attachments/assets/e410fa50-6f0b-4117-a19a-c449be8d1d36

** I need to check the transition for the Tablet landscape. On iOS, the iPad landscape layout is the same as the portrait. We might want to copy that behavior.

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>TransitionState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by MiSikora — CHANGES_REQUESTED** [review]
Transition and animation works really nicely. But the landscape layout broke a bit. It doesn't fit now on my device (Pixel 6).

### Audio

| Before | After |
| - | - |
| Screenshot_20240724-154832 | Screenshot_20240724-155012 |

### Video

| Before | After |
| - | - | 
| Screenshot_20240724-154904 | Screenshot_20240724-154952 |

**Comment by ashiagr** [comment]
I could reproduce it. I fixed it in [5462850](https://github.com/Automattic/pocket-casts-android/pull/2517/commits/546285044f0fe8918550221799a75e7574b2d75a)

Pixel 6 screenshot



I took the screenshot at large font size:

Screenshot 2024-07-25 at 6 34 36 PM

**Review by MiSikora — APPROVED** [review]
LGTM, thanks for fixing it!

**Pull request merged**
