### PR TITLE
Adding Deselect Options to the Multiselect Dialog 

### PR DESCRIPTION
**Pull request by Mzazi25**
## Description

This PR adds multi-select options to the FilterEpisodesListFragment, UpNextFragment, ProfileEpisodeListFragment, PodcastFragment and CloudFilesFragment. 
The deselect functions would pop up when the selectedList size is more than 1, because for the first time, the user would not think of deselecting the list. Deselect options are: Deselect all, Deselect all above and Deselect all below. 
I also switched the position of deselecting below/selecting below with the select all/ deselect all so that the selecting below/deselect below text option is below the select all(check the screenshot attached)

Suggestion maybe: We could improve the icons for deselecting probably instead of the tick checkbox, we can make something like this [X]. 

Fixes # @CookieyedCodes niggles 

## Testing Instructions

1. Tap on Podcast
2. Scroll to the episodes and long press any podcast(this would trigger multi-select)
3. Tap on the selected option(checkout the dialog that pops out(select all above/select all/ select all below)
4. tap on a second multiselect option
5. Long press to check out the new dialog(Deselect all above/ Deselect all/ Deselect all below)
6. Have fun testing the dialog options 

## Screenshots or Screencast 

https://github.com/Automattic/pocket-casts-android/assets/95022986/e6e46257-a41b-457c-a406-d279210c2b95

|   Deselect Dialog    |   Select Dialog  | 
|---	|--- 
 deselect | select 

## Checklist
- [X] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
I did some quick mockups on such icons, as some suggestions considering states, the design team can finalize & give it more thought tho

**Comment by CookieyedCodes** [comment]
@Mzazi25 just so your aware once this part of bookmarks is merged, 🤔 😉 https://github.com/Automattic/pocket-casts-android/pull/1173

**Review by ashiagr — APPROVED** [review]
Works well in my testing. 👍 Code changes look good too.

One thing that I want to be sure of: if we should include a "Select/ Deselect All"  option in this dialog given that it is included in the more options in the top bar. @david-gonzalez-a8c can you confirm that the UI looks ok to you? Also, can you provide us with icons for the deselect options? Thanks! 🙇‍♀️ 

Note: @Mzazi25 don't worry about changes in PR #1173. I can take care of merging this PR.

**Comment by Mzazi25** [comment]
> Works well in my testing. 👍 Code changes look good too.
> 
> One thing that I want to be sure of: if we should include a "Select/ Deselect All" option in this dialog given that it is included in the more options in the top bar. @david-gonzalez-a8c can you confirm that the UI looks ok to you? Also, can you provide us with icons for the deselect options? Thanks! 🙇‍♀️
> 
> Note: @Mzazi25 don't worry about changes in PR #1173. I can take care of merging this PR.

Sure. Thanks. In case of anything, I would be glad to give a hand

**Comment by david-gonzalez-a8c** [comment]
Hello there!

The UI looks good to me. I've prepared some icons for this feature, this is how they look:

image

Please let me know if you need them in additional sizes or formats.

[icons-deselect.zip](https://github.com/Automattic/pocket-casts-android/files/12049624/icons-deselect.zip)

**Comment by CookieyedCodes** [comment]
@david-gonzalez-a8c are these icons designed so they adapt to the theam like the current ones do, just double checking?

**Comment by david-gonzalez-a8c** [comment]
> @david-gonzalez-a8c are these icons designed so they adapt to the theam like the current ones do, just double checking?

The are!

**Comment by Mzazi25** [comment]
@ashiagr I have updated the PR with the suggested icons

**Comment by ashiagr** [comment]
@Mzazi25 can you review merge changes and deselect options for bookmark?

Also, I noticed that we have two different methods `multiSelectSelectNone()` and `multiDeselectAll()` that perform the same action. WDYT about keeping just a single method?

**Comment by Mzazi25** [comment]
Code 

> @Mzazi25 can you review merge changes and deselect options for bookmark?
> 
> Also, I noticed that we have two different methods `multiSelectSelectNone()` and `multiDeselectAll()` that perform the same action. WDYT about keeping just a single method?

Merge Changes LGTM, 
For the two functions, yes we can can remove one  since it does the same thing.

**Comment by Mzazi25** [comment]
@ashiagr I have removed the duplicated `multiDeselectAll()` function. Its better we remain with `multiSelectSelectNone()` since it does the same thing.

**Pull request merged**
