### PR TITLE
Add screen to more easily access logs

### LINKED ISSUE #833: Make it possible to easily view debug logs within the app
### Description

With the recent launch of the [Pocket Casts Forum](https://forums.pocketcasts.com/), we want our users to be able to view their logs easily without having to make a support ticket or go through that flow. It would be great if we could do something similar to the WordPress apps and add an option under Settings to view/export them

### Step-by-step reproduction instructions

At the moment, you need to email yourself the logs. 

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by mchowning**
## Description
This adds a screen to enable the user to more easily access their logs within the app.

> **Note**
> This PR builds on https://github.com/Automattic/pocket-casts-android/pull/910, so you may want to review that one first.

Fixes #833 

## Testing Instructions
1. Go to the Profile tab
2. Tap on the ⚙️ 
3. Tap on "Help & feedback"
4. Tap on the list icon at the top of the screen
5. ✅ Observe that the logs are displayed
6. Tap on the copy icon at the top of the screen
7. ✅  Observe that the logs are copied to the clipboard
8. Tap on the Share icon
9. ✅ Observe that you can share a file with the logs (similar to what happens currently when someone contacts support through the app).

## Screenshots or Screencast 

https://user-images.githubusercontent.com/4656348/234631340-cc39fce0-e5be-44a9-8e4d-9e4ea21d391a.mov

## Checklist
- [X] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] I have considered whether it makes sense to add tests for my changes
- [X] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [X] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [X] with different themes
- [X] with a landscape orientation
- [X] with the device set to have a large display and font size
- [X] for accessibility with TalkBack

### CODE REVIEW

**Comment by CookieyedCodes** [comment]
Would it be a nice function that any errors would be marked with a red ! Or a highlight the line in red to help the user notice the errors?

**Review by ashiagr — APPROVED** [review]
Awesome! Thanks for including this screen 🥇

**Comment by mchowning** [comment]
> Would it be a nice function that any errors would be marked with a red ! Or a highlight the line in red to help the user notice the errors?

That's a good suggestion, but I don't have any immediate plans to work on adding that. If you'd like to open an issue for this, I'll tag it with the `good first issue` label so someone else can pick it up if they're interested.

> Also does this page only show & keep the most recent log, just wondering dose PC keep a cache of logs on device it the page isn't accessed 🤔

This screen doesn't affect the storage of these logs—they're generated on-device and stored in a file on-device regardless of whether the user uses this page. Also, these logs only leave the device if the user chooses to share them either when contacting support from the app or by using the new page in this PR. Adding that screen to more easily view/export the logs is the only change in this PR.

**Comment by CookieyedCodes** [comment]
Fair enough & thanks for clarifying, I still have to figure out how to tag on the github mobile app but I'll figure it out & get to it eventually 😉

**Comment by mchowning** [comment]
I'll probably need to add the tag myself. Permissions issue.

**Pull request merged**
