### PR TITLE
Add open player automatically option in settings

### PR DESCRIPTION
**Pull request by ksog66**
## Description
Adding Open Player Automatically setting option in general player setting, which allows user to choose, if they want to open the full-screen player after they start playing a podcast.

Fixes https://github.com/Automattic/pocket-casts-android/issues/23

## Testing Instructions
1. Go To Profile > Settings > General > Player.
2. Switch on open player automatically option.
3. And start playing a podcast, the full-screen player will open instantly.

## Screenshots or Screencast 
[open-player.webm](https://user-images.githubusercontent.com/70816971/200230359-6e59bd6b-4545-4893-87c9-6063600b9119.webm)

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

**Comment by ksog66** [comment]
Hey @ashiagr, should I update the changelog and add this PR in version 7.27 section

**Comment by ashiagr** [comment]
That'd be great! Thanks 🙂

**Comment by ksog66** [comment]
Hey @ashiagr , I have updated the Changelog.

**Review by ashiagr — APPROVED** [review]
LGTM! 
Thanks for working on it @ksog66 🙏

**Pull request merged**
