### PR TITLE
Migrate auto archive podcast settings to Compose

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This pull request migrates the podcast auto-archive settings to Jetpack Compose. During the migration, I noticed that the previous screen state was sometimes not reflected correctly (but I might have been hallucinating). The migration required the following additions:

* A basic Compose component to display generic radio dialogs.
* A basic Compose component to display a settings row with information only.
* Redesign of the `ToolbarColors` class from a sealed class to a regular class. The sealed implementation was unnecessary as we did not utilize its features anywhere. Making it a regular class also allowed making it parcelable, which improves theme state handling.

### Note on Status Bar Theming

The theming of the status bar is not ideal but is confined to edge cases. For example, while on the podcast auto-archive settings screen, if a user opens the appearance settings, changes the theme, and then returns, the status bar may momentarily flash its color. However, this version suffers from fewer edge cases compared to the previous version.

## Testing Instructions

Do regression tests of the podcast auto archive settings. Check if they are applied correctly and if analytics still work.

### Screen

| Before | After |
| - | - |
| screen-before | screen-after |

### Dialog

| Before | After |
| - | - |
| dialog-after | dialog-before |

## Checklist
- [x] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] ~I have considered whether it makes sense to add tests for my changes~
- [x] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] ~for accessibility with TalkBack~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>PodcastAutoArchiveArgs</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by CookieyedCodes** [comment]
Could we have a 12 hr option for local auto archive?

**Review by mebarbosa — COMMENTED** [review]
My Auto Archive screen is really different the one you shared on screenshot. Not sure what's going on


Screenshot_20240509_123039

**Review by mebarbosa — APPROVED** [review]
Thank you for this PR ❤️ 

It worked as expected and I can confirm tracks still work. Also I tested with different themes and it looks good

**Pull request merged**
